### ISSUE TITLE
Error on createExtension coc-rust-analyzer

### ISSUE THREAD

**Issue by daniel-ferguson** [fannheyward/coc-rust-analyzer#1005]
Hiya, I've just updated to 0.65.0 from 0.64.1 and `coc-rust-analyzer` is now failing to start for me. From the error log pasted below it looks like it's now trying to load a file that doesn't exist (`lib/bridge.js`) - which there's no reference to in the source code as far as I can tell. 

_Please let me know if there's anything further I can do to help you track down the issue._

**What's the output of `:CocInfo`**

```
2022-06-30T17:30:50.500 INFO (pid:45044) [plugin] - coc.nvim initialized with node: v16.13.0 after 87ms
2022-06-30T17:30:51.080 ERROR (pid:45044) [extensions] - Error on createExtension coc-rust-analyzer from /home/daniel/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js Error: ENOENT: no such file or directory, open '/home/daniel/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/bridge.js'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at node_modules/vm2/lib/vm.js (/home/daniel/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:42286:123)
    at __require (/home/daniel/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:25:50)
    at node_modules/vm2/lib/main.js (/home/daniel/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:43703:9)
    at __require (/home/daniel/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:25:50)
    at node_modules/vm2/index.js (/home/daniel/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:43719:23)
    at __require (/home/daniel/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:25:50)
    at node_modules/degenerator/dist/src/index.js (/home/daniel/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:43731:17)
    at __require (/home/daniel/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:25:50) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/daniel/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/bridge.js'
}
2022-06-30T17:30:59.735 INFO (pid:45044) [attach] - receive notification: openLog []
```

**What's the output of `:CocCommand rust-analyzer.serverVersion`**

```
[coc.nvim] Error on notification "runCommand": Command: rust-analyzer.serverVersion not found
```

**Comment by fannheyward** [comment]
Fixed in v0.65.1, sorry for the trouble.
