### ISSUE TITLE
TypeError: c is not iterable

### ISSUE THREAD

**Issue by jbargu** [fannheyward/coc-rust-analyzer#1031]
**What's the output of `:CocInfo`**
```
## versions

vim version: NVIM v0.7.2
node version: v14.17.0
coc.nvim version: 0.0.82-578d2e34 2022-08-10 02:05:48 +0800
coc.nvim directory: /home/nibbles/.dotfiles/vim/vim-plug/coc.nvim
term: screen-256color
platform: linux

## Log of coc.nvim

2022-08-12T13:00:53.015 INFO (pid:1539449) [plugin] - coc.nvim initialized with node: v14.17.0 after 136ms
2022-08-12T13:00:54.483 INFO (pid:1539449) [configurations] - Add folder configuration from file: /home/nibbles/workspace/.vim/coc-settings.json
2022-08-12T13:00:54.487 INFO (pid:1539449) [configurations] - Change folder configuration to: /home/nibbles/workspace/.vim/coc-settings.json
2022-08-12T13:00:54.521 INFO (pid:1539449) [services] - registered service "rust-analyzer"
2022-08-12T13:00:54.522 INFO (pid:1539449) [services] - Rust Analyzer Language Server state change: stopped => starting
2022-08-12T13:00:54.530 INFO (pid:1539449) [language-client-index] - Language server "rust-analyzer" started with 1539536
2022-08-12T13:00:54.542 INFO (pid:1539449) [services] - Rust Analyzer Language Server state change: starting => running
2022-08-12T13:00:54.546 INFO (pid:1539449) [services] - service rust-analyzer started
2022-08-12T13:01:10.990 INFO (pid:1539449) [attach] - receive notification: highlight []
2022-08-12T13:01:21.147 INFO (pid:1539449) [attach] - receive notification: highlight []
2022-08-12T13:01:22.136 INFO (pid:1539449) [attach] - receive notification: highlight []
2022-08-12T13:01:23.661 ERROR (pid:1539449) [server] - unhandledRejection  Promise {
  <rejected> TypeError: c is not iterable
      at /home/nibbles/.dotfiles/vim/vim-plug/coc.nvim/build/index.js:214:23865
      at async Promise.all (index 0)
      at async Bv.provideInlayHints (/home/nibbles/.dotfiles/vim/vim-plug/coc.nvim/build/index.js:214:23710)
      at async VC.renderRange (/home/nibbles/.dotfiles/vim/vim-plug/coc.nvim/build/index.js:303:2643)
} TypeError: c is not iterable
    at /home/nibbles/.dotfiles/vim/vim-plug/coc.nvim/build/index.js:214:23865
    at async Promise.all (index 0)
    at async Bv.provideInlayHints (/home/nibbles/.dotfiles/vim/vim-plug/coc.nvim/build/index.js:214:23710)
    at async VC.renderRange (/home/nibbles/.dotfiles/vim/vim-plug/coc.nvim/build/index.js:303:2643)
2022-08-12T13:01:26.476 INFO (pid:1539449) [attach] - receive notification: highlight []
2022-08-12T13:01:29.119 ERROR (pid:1539449) [server] - unhandledRejection  Promise {
  <rejected> TypeError: c is not iterable
      at /home/nibbles/.dotfiles/vim/vim-plug/coc.nvim/build/index.js:214:23865
      at async Promise.all (index 0)
      at async Bv.provideInlayHints (/home/nibbles/.dotfiles/vim/vim-plug/coc.nvim/build/index.js:214:23710)
      at async VC.renderRange (/home/nibbles/.dotfiles/vim/vim-plug/coc.nvim/build/index.js:303:2643)
} TypeError: c is not iterable
    at /home/nibbles/.dotfiles/vim/vim-plug/coc.nvim/build/index.js:214:23865
    at async Promise.all (index 0)
    at async Bv.provideInlayHints (/home/nibbles/.dotfiles/vim/vim-plug/coc.nvim/build/index.js:214:23710)
    at async VC.renderRange (/home/nibbles/.dotfiles/vim/vim-plug/coc.nvim/build/index.js:303:2643)
2022-08-12T13:01:30.093 INFO (pid:1539449) [attach] - receive notification: highlight []
2022-08-12T13:01:34.098 INFO (pid:1539449) [attach] - receive notification: showInfo []
2022-08-12T13:01:34.582 INFO (pid:1539449) [attach] - receive notification: highlight []
2022-08-12T13:04:06.754 INFO (pid:1539449) [attach] - receive notification: highlight []
2022-08-12T13:04:08.026 INFO (pid:1539449) [attach] - receive notification: highlight []
2022-08-12T13:04:09.503 INFO (pid:1539449) [attach] - receive notification: highlight []
2022-08-12T13:04:13.475 INFO (pid:1539449) [attach] - receive notification: highlight []
2022-08-12T13:04:16.123 ERROR (pid:1539449) [server] - unhandledRejection  Promise {
  <rejected> TypeError: c is not iterable
      at /home/nibbles/.dotfiles/vim/vim-plug/coc.nvim/build/index.js:214:23865
      at async Promise.all (index 0)
      at async Bv.provideInlayHints (/home/nibbles/.dotfiles/vim/vim-plug/coc.nvim/build/index.js:214:23710)
      at async VC.renderRange (/home/nibbles/.dotfiles/vim/vim-plug/coc.nvim/build/index.js:303:2643)
} TypeError: c is not iterable
    at /home/nibbles/.dotfiles/vim/vim-plug/coc.nvim/build/index.js:214:23865
    at async Promise.all (index 0)
    at async Bv.provideInlayHints (/home/nibbles/.dotfiles/vim/vim-plug/coc.nvim/build/index.js:214:23710)
    at async VC.renderRange (/home/nibbles/.dotfiles/vim/vim-plug/coc.nvim/build/index.js:303:2643)
2022-08-12T13:04:16.305 ERROR (pid:1539449) [server] - unhandledRejection  Promise {
  <rejected> TypeError: c is not iterable
      at /home/nibbles/.dotfiles/vim/vim-plug/coc.nvim/build/index.js:214:23865
      at async Promise.all (index 0)
      at async Bv.provideInlayHints (/home/nibbles/.dotfiles/vim/vim-plug/coc.nvim/build/index.js:214:23710)
      at async VC.renderRange (/home/nibbles/.dotfiles/vim/vim-plug/coc.nvim/build/index.js:303:2643)
} TypeError: c is not iterable
    at /home/nibbles/.dotfiles/vim/vim-plug/coc.nvim/build/index.js:214:23865
    at async Promise.all (index 0)
    at async Bv.provideInlayHints (/home/nibbles/.dotfiles/vim/vim-plug/coc.nvim/build/index.js:214:23710)
    at async VC.renderRange (/home/nibbles/.dotfiles/vim/vim-plug/coc.nvim/build/index.js:303:2643)
2022-08-12T13:04:24.268 INFO (pid:1539449) [attach] - receive notification: highlight []
```
**What's the output of `:CocCommand rust-analyzer.serverVersion`**
```
[coc.nvim] rust-analyzer 0.3.1162-standalone (634cfe3d7 2022-08-07)
```
Since upgrading to 0.0.82 coc.vim, some Rust projects show the above notice repeatedly, for others there are no issues (they show the inlay hints).  Turning off `"rust-analyzer.inlayHints.enable": false` does not help.

On a side note, since upgrading, every time I open a Rust project, I get a high CPU usage -> makes my PC go from non-audible to a hovercraft level of noise. This did not happen before. 

- Do you have some suggestions on how to tune parameters (what kind of diagnostics to disable, some other parameters) to reduce this overhead? I tried with ` "rust-analyzer.cachePriming.numThreads": 2`, does not help.
- Is it possible to cache to the disk to disable reindexing everytime I load a project?

**Comment by Fyreway** [comment]
I'm having this exact issue too.

**Comment by fannheyward** [comment]
This has been fixed on https://github.com/neoclide/coc.nvim/pull/4023
