### ISSUE TITLE
Doesn't respect "suggest.noselect": true

### ISSUE THREAD

**Issue by sainnhe** [fannheyward/coc-rust-analyzer#1039]
**What's the output of `:CocInfo`**

```
## versions

vim version: VIM - Vi IMproved 9.0 9000260
node version: v16.17.0
coc.nvim version: 0.0.82-6da029c4 2022-08-24 22:58:55 +0800
coc.nvim directory: /Users/sainnhe/.local/share/nvim/plugins/coc.nvim
term: tmux
platform: darwin

## Log of coc.nvim

2022-08-25T17:00:05.558 ERROR (pid:44587) [configurations] - Invalid configuration "suggest.detailMaxLength" from coc-clangd, overwrite defaults is fobidden.
2022-08-25T17:00:05.559 ERROR (pid:44587) [configurations] - Invalid configuration "diagnostic.format" from coc-clangd, overwrite defaults is fobidden.
2022-08-25T17:00:05.622 INFO (pid:44587) [services] - registered service "diagnostic-languageserver"
2022-08-25T17:00:05.684 INFO (pid:44587) [coc-git] - Looking for git in: git
2022-08-25T17:00:05.695 INFO (pid:44587) [services] - registered service "highlight"
2022-08-25T17:00:05.809 INFO (pid:44587) [services] - registered service "rust-analyzer"
2022-08-25T17:00:05.809 INFO (pid:44587) [services] - Rust Analyzer Language Server state change: stopped => starting
2022-08-25T17:00:05.869 INFO (pid:44587) [plugin] - coc.nvim initialized with node: v16.17.0 after 347ms
2022-08-25T17:00:05.877 WARN (pid:44587) [workspace] - workspace.createStatusBarItem is deprecated, please use window.createStatusBarItem instead. 
    at Object.t.initStatusBar (/Users/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:155873)
    at Object.t.activate (/Users/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:23099)
2022-08-25T17:00:05.899 INFO (pid:44587) [language-client-index] - Language server "rust-analyzer" started with 44946
2022-08-25T17:00:05.926 INFO (pid:44587) [services] - Rust Analyzer Language Server state change: starting => running
2022-08-25T17:00:05.943 INFO (pid:44587) [services] - service rust-analyzer started
2022-08-25T17:00:06.096 INFO (pid:44587) [attach] - receive notification: runCommand [ 'git.refresh' ]
2022-08-25T17:00:06.762 INFO (pid:44587) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'CocDiagnosticChange'
]
2022-08-25T17:00:10.455 INFO (pid:44587) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'CocDiagnosticChange'
]
2022-08-25T17:00:11.702 INFO (pid:44587) [attach] - receive notification: showInfo []
2022-08-25T17:00:11.705 INFO (pid:44587) [attach] - receive notification: doAutocmd [ 1 ]
```

**What's the output of `:CocCommand rust-analyzer.serverVersion`**

`0.0.0`

Maybe because I'm using a locally installed rust-analyzer? I installed RA via macports.

```shell
❯ which rust-analyzer
/opt/local/bin/rust-analyzer
─────────────────────────────────────────────────────────
~/repo/syntax/exa   master                                                                                                                              0.02s sainnhe@macintosh
❯ rust-analyzer --version
rust-analyzer 0.0.0
─────────────────────────────────────────────────────────
~/repo/syntax/exa   master                                                                                                                              0.03s sainnhe@macintosh
❯ port info rust-analyzer
rust-analyzer @20220822 (devel)
Variants:             universal

Description:          rust-analyzer is an experimental modular compiler frontend for the Rust language. It is a part of a larger rls-2.0 effort to create excellent IDE support
                      for Rust.
Homepage:             https://rust-analyzer.github.io

Build Dependencies:   rust, cargo
Platforms:            darwin
License:              Apache-2
Maintainers:          GitHub: fabius
                      Email: herby.gillot@gmail.com, GitHub: herbygillot
                      Policy: openmaintainer
```

---

https://user-images.githubusercontent.com/37491630/186624896-856e5eb9-f4e7-4479-b3d0-3a5e38a5715f.mov

My coc-settings is [here](https://github.com/sainnhe/dotfiles/blob/master/.config/nvim/coc-settings.json).

I set `"suggest.noselect"` to `true`. But when completing variables, coc will always preselect an item.

But when completing macros / functions, this issue doesn't exist.

https://user-images.githubusercontent.com/37491630/186625540-4b8997d4-bfc8-4774-8f2f-80b9067ec480.mov

I can reproduce this bug on both macOS and Arch Linux, both vim 9 and neovim 0.7.2

**Comment by khrynczenko** [comment]
Any updates on this? I have the exact same problem.

**Comment by ShinyJonny** [comment]
I have the same issue.

**Comment by fannheyward** [comment]
This has been fixed on coc.nvim master https://github.com/neoclide/coc.nvim/pull/4224.
