### ISSUE TITLE
Cannot install. Bad response from npmjs.org

### ISSUE THREAD

**Issue by j-greffe** [fannheyward/coc-rust-analyzer#1040]
Hello,
I cannot install the plugging as it seems to be missing something on npmjs.org.

**What's the output of `:CocInfo`**

## versions

vim version: NVIM v0.7.2
node version: v16.17.0
coc.nvim version: 0.0.82-59fa3972 2022-08-29 14:21:58 +0800
coc.nvim directory: /home/jeremie/.cache/dein/repos/github.com/neoclide/coc.nvim_release
term: xterm-256color
platform: linux

## Log of coc.nvim

2022-08-29T16:17:45.804 INFO (pid:340487) [plugin] - coc.nvim initialized with node: v16.17.0 after 33ms
2022-08-29T16:18:02.055 INFO (pid:340487) [attach] - receive notification: installExtensions [ 'coc-rust-analyser' ]
2022-08-29T16:18:02.086 INFO (pid:340487) [model-installer] - Using npm from: /usr/local/bin/npm
2022-08-29T16:18:02.086 INFO (pid:340487) [model-installer] - Get info from https://registry.npmjs.org/
2022-08-29T16:18:02.325 ERROR (pid:340487) [model-fetch] - Fetch error for https://registry.npmjs.org/coc-rust-analyser: {
  method: 'GET',
  hostname: 'registry.npmjs.org',
  port: 443,
  path: '/coc-rust-analyser',
  agent: null,
  rejectUnauthorized: true,
  maxRedirects: 3,
  headers: {
    'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64)',
    'Accept-Encoding': 'gzip, deflate',
    'Proxy-Authorization': null
  },
  timeout: 10000,
  buffer: true
} Error: Bad response from https://registry.npmjs.org/coc-rust-analyser: 404
    at ir.<anonymous> (/home/jeremie/.cache/dein/repos/github.com/neoclide/coc.nvim_release/build/index.js:219:5361)
    at ir.emit (node:events:525:35)
    at ir._processResponse (/home/jeremie/.cache/dein/repos/github.com/neoclide/coc.nvim_release/build/index.js:206:36518)
    at ClientRequest._onNativeResponse (/home/jeremie/.cache/dein/repos/github.com/neoclide/coc.nvim_release/build/index.js:206:32091)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:513:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:674:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:521:22)
    at TLSSocket.emit (node:events:513:28)
2022-08-29T16:18:02.326 ERROR (pid:340487) [extensions] - Error on install coc-rust-analyser Error: Bad response from https://registry.npmjs.org/coc-rust-analyser: 404
    at ir.<anonymous> (/home/jeremie/.cache/dein/repos/github.com/neoclide/coc.nvim_release/build/index.js:219:5361)
    at ir.emit (node:events:525:35)
    at ir._processResponse (/home/jeremie/.cache/dein/repos/github.com/neoclide/coc.nvim_release/build/index.js:206:36518)
    at ClientRequest._onNativeResponse (/home/jeremie/.cache/dein/repos/github.com/neoclide/coc.nvim_release/build/index.js:206:32091)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:513:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:674:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:521:22)
    at TLSSocket.emit (node:events:513:28)
2022-08-29T16:21:48.140 INFO (pid:340487) [attach] - receive notification: showInfo []
{

**What's the output of `:CocCommand rust-analyzer.serverVersion`**

2022-08-29T16:23:47.809 INFO (pid:340487) [attach] - receive notification: runCommand [ 'rust-analyzer.serverVersion' ]
2022-08-29T16:23:47.810 ERROR (pid:340487) [node-client] - Error on notification "runCommand": Command: rust-analyzer.serverVersion not found Error
    at _H.echoError (/home/jeremie/.cache/dein/repos/github.com/neoclide/coc.nvim_release/build/index.js:26:1869)
    at _H.<anonymous> (/home/jeremie/.cache/dein/repos/github.com/neoclide/coc.nvim_release/build/index.js:293:20341)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-08-29T16:23:47.810 ERROR (pid:340487) [attach] - Error: Command: rust-analyzer.serverVersion not found
    at Vie.executeCommand (/home/jeremie/.cache/dein/repos/github.com/neoclide/coc.nvim_release/build/index.js:269:27829)
    at Vie.fireCommand (/home/jeremie/.cache/dein/repos/github.com/neoclide/coc.nvim_release/build/index.js:269:27995)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Bx.runCommand (/home/jeremie/.cache/dein/repos/github.com/neoclide/coc.nvim_release/build/index.js:273:16395)
    at async mC.cocAction (/home/jeremie/.cache/dein/repos/github.com/neoclide/coc.nvim_release/build/index.js:293:18714)
    at async _H.<anonymous> (/home/jeremie/.cache/dein/repos/github.com/neoclide/coc.nvim_release/build/index.js:293:20304)

**Output of `:CocInstall coc-rust-analyser`**

Install finished

- ✗ coc-rust-analyser Bad response from https://registry.npmjs.org/coc-rust-analyser: 404

Best regards.

**Comment by fannheyward** [comment]
It's `coc-rust-analyzer`, you've inputted wrong name.

**Comment by j-greffe** [comment]
Oh my bad :/
Thanks a lot for the quick response.
I have been at it for some time now and i made the same mistake so many times :'|

Have a great day!
