### ISSUE TITLE
coc.nvim gives cannot destructure on code action

### ISSUE THREAD

**Issue by n-0** [fannheyward/coc-rust-analyzer#1053]
Lately after updating my coc.nvim, rust-analyzer extension, autocompletion stopped working.
Does anyone have the same issue or is it a my machine problem?

When I write the name of a function (or sth. else) that I haven't imported yet and
want to trigger the import via autocompletion, coc.nvim fails with the following message

```
[coc.nvim] code action without data use :CocOpenLog for details
[coc.nvim] Error on notification "codeAction": Cannot destructure property 'edit' of 't' as it is undefined.
```

Following the advice the log gives

```
2022-09-15T09:21:25.771 INFO (pid:7060) [attach] - receive notification: codeAction [ 'line' ]
2022-09-15T09:21:27.164 ERROR (pid:7060) [node-client] - code action without data Error: code action without data
    at je (/home/user/.vim/plugged/coc.nvim/build/index.js:29:233)
    at Wi (/home/user/.vim/plugged/coc.nvim/build/index.js:28:6872)
    at Immediate.<anonymous> (/home/user/.vim/plugged/coc.nvim/build/index.js:28:6719)
    at processImmediate (node:internal/timers:466:21)
2022-09-15T09:21:27.165 ERROR (pid:7060) [node-client] - Error on notification "codeAction": Cannot destructure property 'edit' of 't' as it is undefined. Error
    at LH.echoError (/home/user/.vim/plugged/coc.nvim/build/index.js:26:1869)
    at LH.<anonymous> (/home/user/.vim/plugged/coc.nvim/build/index.js:293:20970)
2022-09-15T09:21:27.165 ERROR (pid:7060) [attach] - TypeError: Cannot destructure property 'edit' of 't' as it is undefined.
    at Mx.applyCodeAction (/home/user/.vim/plugged/coc.nvim/build/index.js:273:5568)
    at async Mx.doCodeAction (/home/user/.vim/plugged/coc.nvim/build/index.js:273:4792)
    at async fC.cocAction (/home/user/.vim/plugged/coc.nvim/build/index.js:293:19343)
    at async LH.<anonymous> (/home/user/.vim/plugged/coc.nvim/build/index.js:293:20933)
2022-09-15T09:21:27.220 INFO (pid:7060) [attach] - receive notification: highlight []
```

This happens with all other autocompletion options like complete match arms etc.
Lenses, type information and docs is working great as usual.

**What's the output of `:CocInfo`**
```
vim version: NVIM v0.7.2
node version: v16.17.0
coc.nvim version: 0.0.82-b9c208ef 2022-09-07 15:41:25 +0800
```

**What's the output of `:CocCommand rust-analyzer.serverVersion`**

```
rust-analyzer 0.3.1203-standalone
```

**Comment by fannheyward** [comment]
What's your coc-rust-analyzer version? You can get it from `:CocList extensions`.

**Comment by n-0** [comment]
Thanks for the fast response!
It's
```
coc-rust-analyzer 0.64.0
```

**Comment by fannheyward** [comment]
This should be fixed already, `:CocUpdate` to latest release 0.68.1 and try again.

**Comment by n-0** [comment]
Worked miracles and got a nicer loading popup.
Thanks, issue closed!
