### ISSUE TITLE
coc-fix-current does not work

### ISSUE THREAD

**Issue by drager** [fannheyward/coc-rust-analyzer#1064]
`coc-fix-current` does not work, and says `"doQuickfix": No quickfix action available Error` but the editor and analyzer displays suggestions fine in the editor.

**What's the output of `:CocInfo`**
```vim version: NVIM v0.6.1
node version: v16.17.0
coc.nvim version: 0.0.82-354c751a 2022-10-01 23:51:05 +0800
coc.nvim directory: /home/drager/.local/share/nvim/plugged/coc.nvim
term: xterm-kitty
platform: linux

## Log of coc.nvim

2022-10-03T19:00:09.120 INFO (pid:330240) [plugin] - coc.nvim initialized with node: v16.17.0 after 162ms
2022-10-03T19:00:09.319 INFO (pid:330240) [attach] - receive notification: highlight []
2022-10-03T19:00:09.320 INFO (pid:330240) [attach] - receive notification: highlight []
2022-10-03T19:00:10.349 INFO (pid:330240) [attach] - receive notification: highlight []
2022-10-03T19:00:10.350 INFO (pid:330240) [attach] - receive notification: highlight []
2022-10-03T19:00:11.532 INFO (pid:330240) [services] - registered service "rust-analyzer"
2022-10-03T19:00:11.533 INFO (pid:330240) [services] - LanguageClient Rust Analyzer Language Server state change: stopped => starting
2022-10-03T19:00:11.547 INFO (pid:330240) [language-client-index] - Language server "rust-analyzer" started with 330303
2022-10-03T19:00:11.562 INFO (pid:330240) [services] - LanguageClient Rust Analyzer Language Server state change: starting => running
2022-10-03T19:00:11.581 INFO (pid:330240) [services] - service rust-analyzer started
2022-10-03T19:00:22.269 INFO (pid:330240) [attach] - receive notification: highlight []
2022-10-03T19:00:22.270 INFO (pid:330240) [attach] - receive notification: highlight []
2022-10-03T19:00:30.393 INFO (pid:330240) [attach] - receive notification: highlight []
2022-10-03T19:00:30.393 INFO (pid:330240) [attach] - receive notification: highlight []
2022-10-03T19:00:31.310 INFO (pid:330240) [attach] - receive notification: diagnosticNext []
2022-10-03T19:00:31.823 INFO (pid:330240) [attach] - receive notification: highlight []
2022-10-03T19:00:31.823 INFO (pid:330240) [attach] - receive notification: highlight []
2022-10-03T19:00:32.494 INFO (pid:330240) [attach] - receive notification: diagnosticNext []
2022-10-03T19:00:33.013 INFO (pid:330240) [attach] - receive notification: highlight []
2022-10-03T19:00:33.013 INFO (pid:330240) [attach] - receive notification: highlight []
2022-10-03T19:00:34.078 INFO (pid:330240) [attach] - receive notification: diagnosticNext []
2022-10-03T19:00:37.950 INFO (pid:330240) [attach] - receive notification: highlight []
2022-10-03T19:00:37.951 INFO (pid:330240) [attach] - receive notification: highlight []
2022-10-03T19:00:39.301 INFO (pid:330240) [attach] - receive notification: highlight []
2022-10-03T19:00:39.301 INFO (pid:330240) [attach] - receive notification: highlight []
2022-10-03T19:00:39.734 INFO (pid:330240) [attach] - receive notification: doQuickfix []
2022-10-03T19:00:39.747 ERROR (pid:330240) [node-client] - Error on notification "doQuickfix": No quickfix action available Error
    at b0.echoError (/home/drager/.local/share/nvim/plugged/coc.nvim/build/index.js:22:1869)
    at b0.<anonymous> (/home/drager/.local/share/nvim/plugged/coc.nvim/build/index.js:284:22315)
2022-10-03T19:00:39.747 ERROR (pid:330240) [attach] - Error: No quickfix action available
    at Pb.doQuickfix (/home/drager/.local/share/nvim/plugged/coc.nvim/build/index.js:264:5508)
    at async uy.cocAction (/home/drager/.local/share/nvim/plugged/coc.nvim/build/index.js:284:20774)
    at async b0.<anonymous> (/home/drager/.local/share/nvim/plugged/coc.nvim/build/index.js:284:22278)
2022-10-03T19:00:40.049 INFO (pid:330240) [attach] - receive notification: highlight []
2022-10-03T19:00:40.049 INFO (pid:330240) [attach] - receive notification: highlight []
2022-10-03T19:00:49.590 INFO (pid:330240) [attach] - receive notification: showInfo []
```

**What's the output of `:CocCommand rust-analyzer.serverVersion`**
`rust-analyzer 0.3.1229-standalone `

**What's your coc-rust-analyzer version? You can get it from `:CocList extensions`**
`coc-rust-analyzer 0.68.3 ~/.config/coc/extensions/node_modules/coc-rust-analyzer`

**Comment by fannheyward** [comment]
When you do `coc-fix-current`, coc will find code action for _current_ line, if nothing found, coc posts error `No quickfix action available Error`.

Tested with some code that has code actions, works as expected.

**Comment by drager** [comment]
@fannheyward Right, but I do get errors in my editor though...

![image](https://user-images.githubusercontent.com/1957563/206718304-50075b91-e447-41ac-818b-85c39e1b433b.png)
