### ISSUE TITLE
How do I use modified version of coc-rust-analyzer?

### ISSUE THREAD

**Issue by osa1** [fannheyward/coc-rust-analyzer#1088]
I made changes in coc-rust-analyzer, but I don't know how to install it. The command `:CocInstall ...` installs the upstream version.

How do I install a development version of coc-rust-analyzer?

**Comment by fannheyward** [comment]
Thank you for your testing, you don't need to install it, just set the runtimepath to your local vision.

**Comment by osa1** [comment]
I updated the `runtimepath` and confirmed that it's updated (`:set runtimepath` shows the updated path), but coc is still using upstream coc-rust-analyzer. Do I need to remove it first?

**Comment by osa1** [comment]
Do I need to build coc-rust-analyzer somehow?

**Comment by fannheyward** [comment]
Yes, you need to remove the old version by CocUninstall. You can check the extensions by `:CocList extensions` to make sure you're using your local version. 

Yes, you need to build it with `yarn build`.

**Comment by osa1** [comment]
Thanks. `yarn build` fails with this:

```
yarn run v1.22.19
warning coc-rust-analyzer@0.71.0: The engine "coc" appears to be invalid.
$ node esbuild.js
Error: Cannot find module 'esbuild'
Require stack:
- /home/omer/other/coc-rust-analyzer/esbuild.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at start (/home/omer/other/coc-rust-analyzer/esbuild.js:3:9)
    at Object.<anonymous> (/home/omer/other/coc-rust-analyzer/esbuild.js:31:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/omer/other/coc-rust-analyzer/esbuild.js' ]
}
Done in 0.09s.
```

What do I do?

**Comment by fannheyward** [comment]
Run `yarn install` first.

**Comment by osa1** [comment]
Thanks!
