### ISSUE TITLE
Rust Analyzer not recognized when installed via Homebrew

### ISSUE THREAD

**Issue by martin-braun** [fannheyward/coc-rust-analyzer#1100]
On macOS 12.6 (21G115) I installed rust-analyzer via `brew install rust-analyzer`. Output of `rust-analyzer --version` is `rust-analyzer 0.0.0 (f77b68a3c 2023-01-08)` (is this right?).

`coc-rust-analyzer` will still ask to install it: 

<img width="535" alt="Rust Analyzer is not found, download from GitHub release? 1. Yes 2. Cancel" src="https://user-images.githubusercontent.com/24259245/212154261-7dd3d5e0-6ca7-4887-abea-842ec6c171bf.png">

**What's the output of `:CocInfo`**

```
## versions

vim version: NVIM v0.8.2
node version: v18.13.0
coc.nvim version: 0.0.82-b11a93ba 2022-12-25 15:19:13 +0800
coc.nvim directory: /Users/marty/.local/share/nvim/site/pack/packer/opt/coc.nvim
term: iTerm.app
platform: darwin

## Log of coc.nvim

2023-01-12T19:52:20.175 WARN (pid:99341) [workspace] - workspace.createOutputChannel is deprecated, please use window.createOutputChannel instead. 
    at Object.<anonymous> (/Users/marty/.config/coc/extensions/node_modules/coc-tailwindcss/out/index.js:14:7870)
    at Generator.next (<anonymous>)
2023-01-12T19:52:20.347 INFO (pid:99341) [plugin] - coc.nvim initialized with node: v18.13.0 after 526
2023-01-12T19:52:20.350 INFO (pid:99341) [attach] - receive notification: highlight []
2023-01-12T19:52:21.789 WARN (pid:99341) [workspace] - workspace.createStatusBarItem is deprecated, please use window.createStatusBarItem instead. 
    at Object.<anonymous> (/Users/marty/.config/coc/extensions/node_modules/coc-rls/lib/index.js:5711:39)
    at __webpack_require__ (/Users/marty/.config/coc/extensions/node_modules/coc-rls/lib/index.js:20:30)
2023-01-12T19:52:21.791 WARN (pid:99341) [workspace] - workspace.createOutputChannel is deprecated, please use window.createOutputChannel instead. 
    at Object.<anonymous> (/Users/marty/.config/coc/extensions/node_modules/coc-rls/lib/index.js:131:44)
    at Generator.next (<anonymous>)
2023-01-12T19:52:21.941 INFO (pid:99341) [extension:coc-rls] - Detected active channel: stable-x86_64-apple-darwin (since 'rust-client.channel' is unspecified)
2023-01-12T19:52:22.131 INFO (pid:99341) [extension:coc-rls] - Detected active channel: stable-x86_64-apple-darwin (since 'rust-client.channel' is unspecified)
2023-01-12T19:52:26.800 ERROR (pid:99341) [timing] - activate coc-rust-analyzer timeout after 5000ms
2023-01-12T19:52:45.859 INFO (pid:99341) [attach] - receive notification: highlight []
```

**What's the output of `:CocCommand rust-analyzer.serverVersion`**

```
[coc.nvim]: Error on notification "runCommand": Command: rust-analyzer.serverVersion not found
```

**What's your coc-rust-analyzer version? You can get it from `:CocList extensions`**

```
* coc-rust-analyzer 0.71.1 ~/.config/coc/extensions/node_modules/coc-rust-analyzer
```

**Comment by fannheyward** [comment]
Set `rust-analyzer.server.path` to `rust-analyzer`, coc-rust-analyzer will find it from PATH to use.
