### ISSUE TITLE
Usage without cargo

### ISSUE THREAD

**Issue by mladedav** [fannheyward/coc-rust-analyzer#1102]
Thanks for the extension, sorry if this has been asked before.

Sometimes when I just want to quickly test some minor detail I'd like to just write a file, call `rustc` directly and not create a whole cargo project. Currently, when I open a .rs file that is not part of a cargo project I get just a few suggestions based on often-used words (like `deref`, `derive`), but no contextual help.

Is it possible for coc-rust-analyzer to analyze single files without a cargo project?

For reference, it seems rust-analyzer should be able to do this according to maintainers, although other frontends also seem to struggle with this: https://github.com/rust-lang/rust-analyzer/issues/12310

**What's the output of `:CocInfo`**
```
## versions

vim version: VIM - Vi IMproved 9.0 9000749
node version: v16.15.1
coc.nvim version: 0.0.82-eca69a9 2023-01-23 23:48:14 +0800
coc.nvim directory: /home/mladedav/.vim/plugged/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2023-01-25T03:29:53.741 INFO (pid:18889) [plugin] - coc.nvim initialized with node: v16.15.1 after 153
2023-01-25T03:29:53.743 INFO (pid:18889) [services] - LanguageClient Rust Analyzer Language Server state change: stopped => starting
2023-01-25T03:29:53.750 INFO (pid:18889) [language-client-index] - Language server "rust-analyzer" started with 18903
2023-01-25T03:29:53.763 INFO (pid:18889) [services] - LanguageClient Rust Analyzer Language Server state change: starting => running
2023-01-25T03:29:53.770 INFO (pid:18889) [services] - service rust-analyzer started
```
**What's the output of `:CocCommand rust-analyzer.serverVersion`**
```
[coc.nvim] rust-analyzer 0.3.1377-standalone
```
**What's your coc-rust-analyzer version? You can get it from `:CocList extensions`**
0.71.1

**Comment by fannheyward** [comment]
`rust-analzyer` supports standalone rust file mode, coc-rust-analzyer also support this.

1. `mkdir ~/demo && cd ~/demo`
2. `touch main.rs`
3. `vim main.ts`, rust-analyzer works as expected.

**Comment by mladedav** [comment]
Ok, I've played around with this and it does run, but it only offers completions for standard types, not types that are declared in the same file. It also doesn't highlight issues such as using a non-existent function. Should these things also work?

**Comment by mladedav** [comment]
I've tried once more to compare the functionality between standalone files in vim and VS Code.

rust-analyzer in VS Code with a standalone file provides all the help that is standard for cargo projects. Some functionality does not work like running the project, but suggestions are ok.
![image](https://user-images.githubusercontent.com/16705820/216036824-f6c1c943-8943-4db1-a8c9-50a88fbfd54f.png)

Vim with cargo project provides contextual suggestions:
![image](https://user-images.githubusercontent.com/16705820/216037269-bc8ccace-ad20-4a36-8b7c-af664b5ad78f.png)

Vim standalone file doesn't automatically provide any contextual suggestions and only offers things that are often used when at least one letter is written.
![image](https://user-images.githubusercontent.com/16705820/216037568-0156cb86-b361-4c43-a82e-5e5577c6eb53.png)

![image](https://user-images.githubusercontent.com/16705820/216037751-556dbd02-ba9e-459f-a404-754a6d89693f.png)

Does this work differently for you?

**Comment by ErrorNoInternet** [comment]
Same issue here.

**Comment by ubordignon** [comment]
> `rust-analzyer` supports standalone rust file mode, coc-rust-analzyer also support this.
> 
>     * [Again no Support for standalone files (no Cargo.toml) #1014](https://github.com/fannheyward/coc-rust-analyzer/issues/1014)
> 
>     * [Support for standalone files (no Cargo.toml) #828](https://github.com/fannheyward/coc-rust-analyzer/issues/828)
> 
> 
>     1. `mkdir ~/demo && cd ~/demo`
> 
>     2. `touch main.rs`
> 
>     3. `vim main.ts`, rust-analyzer works as expected.

Hi! I would like to request the issue be re-opened because I am unable to reproduce the solution.

**What's the output of `:CocInfo`**
```bash
## versions

vim version: NVIM v0.10.0
node version: v20.14.0
coc.nvim version: 0.0.82-2c7e7156 2024-05-15 09:42:33 +0800
coc.nvim directory: /home/$my_user/.local/share/nvim/plugged/coc.nvim
term: alacritty
platform: linux

## Log of coc.nvim

2024-06-02T22:11:07.435 INFO (pid:415679) [plugin] - coc.nvim initialized with node: v20.14.0 after 87
2024-06-02T22:11:07.435 INFO (pid:415679) [services] - LanguageClient Rust Analyzer Language Server state change: stopped => starting
2024-06-02T22:11:07.439 INFO (pid:415679) [language-client-index] - Language server "rust-analyzer" started with 415691
2024-06-02T22:11:07.445 INFO (pid:415679) [services] - LanguageClient Rust Analyzer Language Server state change: starting => running
2024-06-02T22:11:07.448 INFO (pid:415679) [services] - service rust-analyzer started
2024-06-02T22:11:11.734 INFO (pid:415679) [attach] - receive notification: showInfo []
2024-06-02T22:11:20.449 INFO (pid:415679) [attach] - Request action: hasProvider [ 'hover' ]
2024-06-02T22:11:20.451 INFO (pid:415679) [attach] - receive notification: doHover []
2024-06-02T22:11:23.687 INFO (pid:415679) [attach] - receive notification: showInfo []
2024-06-02T22:11:39.595 INFO (pid:415679) [attach] - receive notification: showInfo []
2024-06-02T22:12:12.261 ERROR (pid:415679) [provider-manager] - Provider error on provideHover: _ResponseError: content modified
    at handleResponse (/home/$my_user/.local/share/nvim/plugged/coc.nvim/build/index.js:20190:40)
    at handleMessage (/home/$my_user/.local/share/nvim/plugged/coc.nvim/build/index.js:20000:11)
    at processMessageQueue (/home/$my_user/.local/share/nvim/plugged/coc.nvim/build/index.js:20015:13)
    at Immediate.<anonymous> (/home/$my_user/.local/share/nvim/plugged/coc.nvim/build/index.js:19991:11)
    at process.processImmediate (node:internal/timers:478:21) {
  code: -32801,
  data: undefined
}
2024-06-02T22:13:50.542 INFO (pid:415679) [attach] - receive notification: showInfo []
2024-06-02T22:14:04.982 INFO (pid:415679) [attach] - Request action: hasProvider [ 'hover' ]
2024-06-02T22:14:04.984 INFO (pid:415679) [attach] - receive notification: doHover []
2024-06-02T22:14:07.794 INFO (pid:415679) [attach] - receive notification: jumpDefinition []
```

**What's the output of `:CocCommand rust-analyzer.serverVersion`**

```bash
[coc.nvim] rust-analyzer 1 (71a816a90f 2024-05-26)
```

**What's your coc-rust-analyzer version? You can get it from `:CocList extensions`**

```bash
coc-rust-analyzer 0.76.1
```

I am unable to get anything back from the extension, which works perfectly fine with regular Cargo projects. I tried to log more extensively with RA_LOG=debug but I can't make heads or tails of what the problem is. I tried to rule out whether it might be something to do with other coc.nvim or plug.nvim extensions by using a different init.vim file and coc-settings.json location, along with a new data folder for coc extensions. I also excluded the home folder along with cargo and rustup folders from the workspace folders - although I'm not sure it applies in this scenario.

Could you help please?

**Comment by fannheyward** [comment]
> Once I removed it and reinstalled it with rustup, I was able to get the plugin working.

Why do you think it's bug of coc-rust-analyzer?
