### ISSUE TITLE
[coc.nvim] Rust Analyzer Language Server client: couldn't create connection to server.

### ISSUE THREAD

**Issue by baby195lxl** [fannheyward/coc-rust-analyzer#1196]
**What's the output of `:CocInfo`**
## versions

vim version: VIM - Vi IMproved 9.0 9002063
node version: v18.17.1
coc.nvim version: 0.0.82-d1568d56 2023-09-29 19:43:34 +0800
coc.nvim directory: /home/romo/.vim/plugged/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2023-10-27T22:01:19.684 INFO (pid:1703) [plugin] - coc.nvim initialized with node: v18.17.1 after 253
2023-10-27T22:01:19.686 INFO (pid:1703) [services] - LanguageClient Rust Analyzer Language Server state change: stopped => starting
2023-10-27T22:01:19.697 INFO (pid:1703) [language-client-index] - Language server "rust-analyzer" started with 1717
2023-10-27T22:01:20.384 INFO (pid:1703) [services] - LanguageClient Rust Analyzer Language Server state change: starting => stopped
2023-10-27T22:01:20.384 INFO (pid:1703) [services] - LanguageClient Rust Analyzer Language Server state change: stopped => starting
2023-10-27T22:01:20.389 ERROR (pid:1703) [language-client-client] - Server rust-analyzer initialization failed. Dg [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/home/romo/.vim/plugged/coc.nvim/build/index.js:52:4644)
    at Object.dispose (/home/romo/.vim/plugged/coc.nvim/build/index.js:237:6192)
    at Md.handleConnectionClosed (/home/romo/.vim/plugged/coc.nvim/build/index.js:240:15472)
    at Md.handleConnectionClosed (/home/romo/.vim/plugged/coc.nvim/build/index.js:244:3541)
    at t (/home/romo/.vim/plugged/coc.nvim/build/index.js:240:15121)
    at xP.invoke (/home/romo/.vim/plugged/coc.nvim/build/index.js:24:14497)
    at oh.fire (/home/romo/.vim/plugged/coc.nvim/build/index.js:24:15266)
    at et (/home/romo/.vim/plugged/coc.nvim/build/index.js:26:7064)
    at xP.invoke (/home/romo/.vim/plugged/coc.nvim/build/index.js:24:14497)
    at oh.fire (/home/romo/.vim/plugged/coc.nvim/build/index.js:24:15266) {
  code: -32097,
  data: undefined
}

**What's the output of `:CocCommand rust-analyzer.serverVersion`**

nothing

**What's your coc-rust-analyzer version? You can get it from `:CocList extensions`**
+ coc-rust-analyzer 0.75.0 ~/.config/coc/extensions/node_modules/coc-rust-analyzer                                                                                          
 + coc-pyright 1.1.332 ~/.config/coc/extensions/node_modules/coc-pyright

i have try reinstall the coc-rust-analyzer many time, but it seems no helpful, Is it something I did wrong in the installation steps?Thank you for your response

**Comment by fannheyward** [comment]
Make sure you've installed rust-analyzer successfully.

**Comment by baby195lxl** [comment]
> Make sure you've installed rust-analyzer successfully.

Thank you for your response. In the past, after installing coc-rust-analyzer, it would automatically prompt me to install rust-analyzer, but this time it didn't, so I thought there might be some other issue.
