### ISSUE TITLE
couldn't create connection to server.

### ISSUE THREAD

**Issue by mattveraldi** [fannheyward/coc-rust-analyzer#1205]
I am unable to use this coc extension. This error comes from a fresh install.

**What's the output of `:CocInfo`**
## versions 
vim version: VIM - Vi IMproved 8.2 8021847   
node version: v20.9.0                             
coc.nvim version: 0.0.82-d1568d56 2023-09-29 19:43:34 +0800 
coc.nvim directory: /home/mveraldi/.vim/plugged/coc.nvim
term: dumb                      
platform: linux

**What's the output of `:CocCommand rust-analyzer.serverVersion`**
[coc.nvim]: Error on notification "runCommand": Command: rust-analyzer.serverVersion not found

**What's your coc-rust-analyzer version? You can get it from `:CocList extensions`**
0.75.0
**Output of :CocOpenLog**
```
2023-11-16T00:36:57.229 ERROR (pid:17550) [language-client-client] - Server rust-analyzer initialization failed. Dg [Error]: Pending response rejected since connection got disposed
    at Object.dispose ^[[90m(/home/mveraldi/^[[39m.vim/plugged/coc.nvim/build/index.js:52:4644^[[90m)^[[39m
    at Object.dispose ^[[90m(/home/mveraldi/^[[39m.vim/plugged/coc.nvim/build/index.js:237:6192^[[90m)^[[39m
    at Md.handleConnectionClosed ^[[90m(/home/mveraldi/^[[39m.vim/plugged/coc.nvim/build/index.js:240:15472^[[90m)^[[39m    at Md.handleConnectionClosed ^[[90m(/home/mveraldi/^[[39m.vim/plugged/coc.nvim/build/index.js:244:3541^[[90m)^[[39m
    at t ^[[90m(/home/mveraldi/^[[39m.vim/plugged/coc.nvim/build/index.js:240:15121^[[90m)^[[39m
    at xP.invoke ^[[90m(/home/mveraldi/^[[39m.vim/plugged/coc.nvim/build/index.js:24:14497^[[90m)^[[39m
    at oh.fire ^[[90m(/home/mveraldi/^[[39m.vim/plugged/coc.nvim/build/index.js:24:15266^[[90m)^[[39m
    at et ^[[90m(/home/mveraldi/^[[39m.vim/plugged/coc.nvim/build/index.js:26:7064^[[90m)^[[39m
    at xP.invoke ^[[90m(/home/mveraldi/^[[39m.vim/plugged/coc.nvim/build/index.js:24:14497^[[90m)^[[39m
    at oh.fire ^[[90m(/home/mveraldi/^[[39m.vim/plugged/coc.nvim/build/index.js:24:15266^[[90m)^[[39m {
  code: ^[[33m-32097^[[39m,
  data: ^[[90mundefined^[[39m
}
```

**Comment by fannheyward** [comment]
Make sure you have rust-analyzer installed successfully.

**Comment by mattveraldi** [comment]
My bad, thank you.
