### ISSUE TITLE
How to disable the documentation in pmenu

### ISSUE THREAD

**Issue by Bee-Mar** [fannheyward/coc-rust-analyzer#1207]
**Issue:**
This may be the wrong place for this question/issue, but I cannot for the life of me figure out how to disable the documentation opening next to the completion suggestion (shown in the screenshot):

![2023-11-30-112118_1920x1080_scrot](https://github.com/fannheyward/coc-rust-analyzer/assets/17814198/2424e77d-3bd2-4cda-9675-000432be60de)

**Description**
I've attempted to set `"rust-analyzer.signatureInfo.documentation.enable": false` thinking it would be related to the signature shown in the completion menu, but that didn't solve it. Is there any idea of how to modify this? I've also tried setting `completeopt` to various settings to no avail either.

-------------------------------

**What's the output of `:CocInfo`**
```
## versions

vim version: NVIM v0.10.0-dev
node version: v18.16.0
coc.nvim version: 0.0.82-d1568d56 2023-09-29 19:43:34 +0800
coc.nvim directory: /home/bmarlowe/.vim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2023-11-30T11:22:35.730 INFO (pid:16347) [attach] - receive notification: registerNotification [ 'cquery', '$cquery/publishSemanticHighlighting' ]
2023-11-30T11:22:35.731 INFO (pid:16347) [attach] - receive notification: registerNotification [ 'cquery', '$cquery/setInactiveRegions' ]
2023-11-30T11:22:35.731 INFO (pid:16347) [attach] - receive notification: registerNotification [ 'ccls', '$ccls/publishSemanticHighlight' ]
2023-11-30T11:22:35.732 INFO (pid:16347) [attach] - receive notification: registerNotification [ 'ccls', '$ccls/publishSkippedRanges' ]
2023-11-30T11:22:35.732 INFO (pid:16347) [attach] - receive notification: highlight []
2023-11-30T11:22:35.861 INFO (pid:16347) [extension:coc-git] - Looking for git in: git
2023-11-30T11:22:35.987 WARN (pid:16347) [workspace] - workspace.createStatusBarItem is deprecated, please use window.createStatusBarItem instead. 
    at new t.Actions (/home/bmarlowe/.config/coc/extensions/node_modules/coc-actions/out/index.js:1:8301)
    at t.activate (/home/bmarlowe/.config/coc/extensions/node_modules/coc-actions/out/index.js:1:15288)
2023-11-30T11:22:36.028 INFO (pid:16347) [plugin] - coc.nvim initialized with node: v18.16.0 after 384
2023-11-30T11:22:36.034 WARN (pid:16347) [workspace] - workspace.createStatusBarItem is deprecated, please use window.createStatusBarItem instead. 
    at t.initStatusBar (/home/bmarlowe/.config/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:156009)
    at t.activate (/home/bmarlowe/.config/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:23162)
2023-11-30T11:22:36.052 INFO (pid:16347) [language-client-index] - Language server "cSpell" started with 16367
2023-11-30T11:22:36.111 INFO (pid:16347) [attach] - receive notification: registerNotification [ 'cquery', '$cquery/publishSemanticHighlighting' ]
2023-11-30T11:22:36.112 INFO (pid:16347) [attach] - receive notification: registerNotification [ 'cquery', '$cquery/setInactiveRegions' ]
2023-11-30T11:22:36.112 INFO (pid:16347) [attach] - receive notification: registerNotification [ 'ccls', '$ccls/publishSemanticHighlight' ]
2023-11-30T11:22:36.112 INFO (pid:16347) [attach] - receive notification: registerNotification [ 'ccls', '$ccls/publishSkippedRanges' ]
```

**What's the output of `:CocCommand rust-analyzer.serverVersion`**

**What's your coc-rust-analyzer version? You can get it from `:CocList extensions`**
0.75.0

**Comment by fannheyward** [comment]
`"suggest.enableFloat": false` in your coc-settings.json, check `:h coc-config-suggest-enableFloat`.
