### ISSUE TITLE
v0.4.5 errors

### ISSUE THREAD

**Issue by JoshMcguigan** [fannheyward/coc-rust-analyzer#162]
Thanks for your work maintaining this plugin. I've noticed since the v0.4.5 update I started getting an error on startup. It seems to show up the first time I open a `.rs` file.

```
   22 2020-03-10T04:13:53.991 INFO (pid:1574866) [services] - registed service "rust-analyzer"
   23 2020-03-10T04:13:53.995 INFO (pid:1574866) [language-client-index] - rust-analyzer started with 1574999
   24 2020-03-10T04:13:53.997 INFO (pid:1574866) [services] - Rust Analyzer Language Server state change: starting => running
   25 2020-03-10T04:13:53.999 ERROR (pid:1574866) [extensions] - TypeError: client.onProgress is not a function
   26     at /home/josh/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:8194:16
   27     at Ctx.startServer (/home/josh/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:6050:13)
   28     at async Object.activate (/home/josh/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:132:5)
   29     at async Object.activate (/home/josh/.vim/plugged/coc.nvim/build/index.js:58421:31)
```
I also get an error when attempting to use the `fill match arms` code action:

```
[coc.nvim] Execute 'rust-analyzer.applySourceChange error: Error: unknown request'
```

Finally, it seems the rust-analyzer plugin isn't registering commands with coc. I get no autocomplete if I try to `:CocCommand rust-an<TAB>`, and if I enter a command manually I get:

```
[coc.nvim] Command: rust-analyzer.reload not found
```

I've confirmed that none of these are there if I downgrade to v0.4.4.

Let me know if there is anything further I can do to help troubleshoot or fix this issue!

**Comment by JoshMcguigan** [comment]
I resolved this by updating coc from `0.0.74` to `0.0.76`. 

Thanks again for your work on the plugin!
