### ISSUE TITLE
"create module" assist fails to open created file

### ISSUE THREAD

**Issue by TimoFreiberg** [fannheyward/coc-rust-analyzer#199]
When running the "create module" assist, I get the following prompt:
```
1 documents on disk would be loaded for change, confirm?
[Y]es, (N)o: 
```
No matter what I choose, I stay in the current file and get the following error:
```
2020-04-19T11:39:14.479 ERROR (pid:16623) [commands] - Error: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "/home/tf/Projects/rust/test-create-mod/src/foo.rs", query: "", fragment: ""}
    at _validateUri (/home/tf/.local/share/nvim/plugged/coc.nvim/build/index.js:21303:19)
    at _URI.URI (/home/tf/.local/share/nvim/plugged/coc.nvim/build/index.js:21405:13)
    at new _URI (/home/tf/.local/share/nvim/plugged/coc.nvim/build/index.js:21607:47)
    at Function.URI.parse (/home/tf/.local/share/nvim/plugged/coc.nvim/build/index.js:21517:16)
    at Workspace.getDocument (/home/tf/.local/share/nvim/plugged/coc.nvim/build/index.js:24569:32)
    at Workspace.readFile (/home/tf/.local/share/nvim/plugged/coc.nvim/build/index.js:24868:29)
    at Object.applySourceChange (/home/tf/.local/share/nvim/plugged/coc-rust-analyzer/lib/index.js:5553:36)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/tf/.local/share/nvim/plugged/coc-rust-analyzer/lib/index.js:227:9
```

I didn't manage to add logging [here](https://github.com/fannheyward/coc-rust-analyzer/blob/ea2d7036cda4fa071b11f3e7bf5429bc372d3a28/src/source_change.ts#L28), so I'm not sure if this is a bug in coc-rust-analyzer, coc.nvim or my config.

Do you know if it's possible to disable the `1 documents on disk would be loaded for change, confirm?` prompt?

**Comment by TimoFreiberg** [comment]
Oh, now that I look at [the readFile implementation in coc.nvim](https://github.com/neoclide/coc.nvim/blob/4d46a3d5695cead26cf1e6bcb5d659a652769164/src/workspace.ts#L757), it looks like it should just be called with `toOpen` (because `readFile` calls `URI.parse` and uses its `fsPath`)
Is that right?

**Comment by fannheyward** [comment]
Thanks for your report, I've fixed the url. But jump will not works currently https://github.com/neoclide/coc.nvim/pull/1796

**Comment by TimoFreiberg** [comment]
Thanks for the quick fix!

**Comment by fannheyward** [comment]
New version has released. You also need to upgrade your coc.nvim to latest.

**Comment by JeanMertz** [comment]
Could this still (or again) be an issue?

When I hover over a ` mod mymod {}`, do `:CodeAction` and select `Extract module to file`, two things happen:

1. I get a pop-up asking "1 documents on disk would be loaded for change, confirm? (y/n)?"
2. If I press `y`, the file `src/mymod.rs` is created.

Nothing else happens. The `mymod.rs` file remains empty, and the current inline module isn't removed.
