### ISSUE TITLE
UnhandledRejection: TypeError

### ISSUE THREAD

**Issue by Torrencem** [fannheyward/coc-rust-analyzer#225]
Since I updated fairly recently, whenever I open a rust project I continuously get errors from coc.nvim. The error says:

```
[coc.nvim] error: UnhandledRejection: TypeError: this.ctx.sendRequestWithRetry(...).catch(...).finally is not a function
```

Heres the coc.nvim log:

```
    8   <rejected> TypeError: this.ctx.sendRequestWithRetry(...).catch(...).finally is not a function
    9     at HintsUpdater.fetchHints (/home/matt/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js: 8258:21)
   10     at sourceFiles.forEach (/home/matt/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:8219:54)
   11     at Map.forEach (<anonymous>)
   12     at HintsUpdater.syncCacheAndRenderHints (/home/matt/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:8219:26)
   13     at new HintsUpdater (/home/matt/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:8211:14)
   14     at Object.onConfigChange (/home/matt/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:8278:32)
   15     at <anonymous>
   16     at process._tickCallback (internal/process/next_tick.js:188:7) } TypeError: this.ctx.sendRequestWithRetry(...).catch(...).finally is not a function
   17     at HintsUpdater.fetchHints (/home/matt/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:8258:21)
   18     at sourceFiles.forEach (/home/matt/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:8219:54)
   19     at Map.forEach (<anonymous>)
   20     at HintsUpdater.syncCacheAndRenderHints (/home/matt/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:8219:26)
   21     at new HintsUpdater (/home/matt/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:8211:14)
   22     at Object.onConfigChange (/home/matt/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:8278:32)
   23     at <anonymous>
   24     at process._tickCallback (internal/process/next_tick.js:188:7)
```

Sorry for any weird formatting, it was a pain to copy/paste.

From a bunch of random searching, it looks like it was caused by [this commit here](https://github.com/fannheyward/coc-rust-analyzer/commit/3a27c8745cc85f6ac1c493cdbe87f8ef0b287357) handing something it wasn't supposed to to coc (that's about as specific as I can be)

(edit)

[here's the specific line](https://github.com/fannheyward/coc-rust-analyzer/commit/3a27c8745cc85f6ac1c493cdbe87f8ef0b287357#diff-6468f98775c0bffcecf0c3683bb2002dR105) that's causing problems

Adding 

```
{
    "rust-analyzer.inlayHints.chainingHints": "false"
}
```

to coc-settings.json does not fix the problem

**Comment by Torrencem** [comment]
Work-around for those who just want to use 0.5.5:

```
:CocUninstall coc-rust-analyzer
:CocInstall coc-rust-analyzer@0.5.5
```

took some googling to figure out that that was possible! You should also probably add
```
"coc.preferences.extensionUpdateCheck": "never"
```
to coc-settings.json (:CocConfig)

**Comment by fannheyward** [comment]
What’s your node version?

**Comment by Torrencem** [comment]
```
$ npm --version
3.5.2
$ node --version
v8.10.0
$ nvim --version
NVIM v0.4.3
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-9a287301-34f2-4b86-92e3-462594f51f36

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim
"

Run :checkhealth for more info

(:CocInfo gives)
vim version: NVIM v0.4.3
node version: v8.10.0
coc.nvim version: 0.0.78-030aef2f6d
term: xterm-256color
platform: linux
```

**Comment by Torrencem** [comment]
Curiously, it works fine on my other computer:
```
$ npm --version
6.14.4
$ node --version
v10.20.1
```
Also linux

**Comment by Torrencem** [comment]
I did
```
sudo apt-get remove nodejs
```
then followed the instructions [here](https://www.ostechnix.com/install-node-js-linux/) to get the latest version of node (v14.1.0), this solved the problem!
