### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by anouarkappitou** [fannheyward/coc-rust-analyzer#227]
I tried 'rust-analyzer' without any plugin yesterday, and seems to work perfectly, but after adding coc-rust-analyzer i got the following error:

`2020-05-02T14:17:18.457 INFO (pid:526) [plugin] - coc 0.0.78-030aef2f6d initialized with node: v8.10.0

 23 2020-05-02T14:17:23.491 INFO (pid:526) [services] - registered service "rust-analyzer"

 22 2020-05-02T14:17:23.492 INFO (pid:526) [services] - Rust Analyzer Language Server state change: stopped => starting

 21 2020-05-02T14:17:23.547 INFO (pid:526) [language-client-index] - rust-analyzer started with 538

 20 2020-05-02T14:17:23.560 ERROR (pid:526) [language-client-client] - connection error: { Error: write EPIPE

 19     at _errnoException (util.js:1022:11)

 18     at WriteWrap.afterWrite [as oncomplete] (net.js:880:14) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' } undefined

 17 2020-05-02T14:17:25.290 INFO (pid:526) [services] - Rust Analyzer Language Server state change: starting => stopped

 16 2020-05-02T14:17:25.292 ERROR (pid:526) [language-client-client] - connection error: Error: This socket is closed

 15     at Socket._writeGeneric (net.js:739:18)

 14     at Socket._write (net.js:799:8)

 13     at doWrite (_stream_writable.js:397:12)

 12     at writeOrBuffer (_stream_writable.js:383:5)

 11     at Socket.Writable.write (_stream_writable.js:290:11)

 10     at Socket.write (net.js:717:40)

  9     at StreamMessageWriter.write (/home/anouar/.vim/plugged/coc.nvim/build/index.js:17174:27)

  8     at Promise (/home/anouar/.vim/plugged/coc.nvim/build/index.js:16322:35)

  7     at new Promise (<anonymous>)

  6     at Object.sendRequest (/home/anouar/.vim/plugged/coc.nvim/build/index.js:16312:26) undefined

  5 2020-05-02T14:17:25.293 ERROR (pid:526) [language-client-client] - connection error: Error: This socket is closed

  4     at Socket._writeGeneric (net.js:739:18)

  3     at Socket._write (net.js:799:8)

  2     at doWrite (_stream_writable.js:397:12)

  1     at writeOrBuffer (_stream_writable.js:383:5)

  0     at Socket.Writable.write (_stream_writable.js:290:11)

  1     at Socket.write (net.js:717:40)

  2     at StreamMessageWriter.write (/home/anouar/.vim/plugged/coc.nvim/build/index.js:17176:27)

  3     at Promise (/home/anouar/.vim/plugged/coc.nvim/build/index.js:16322:35)

  4     at new Promise (<anonymous>)

  5     at Object.sendRequest (/home/anouar/.vim/plugged/coc.nvim/build/index.js:16312:26) undefined`

**Comment by fannheyward** [comment]
Try to upgrade your node version to 10+.

**Comment by anouarkappitou** [comment]
I upgraded node to v12.16.3 but it persists.

### CocOpenLog output

```2020-05-02T14:37:39.492 INFO (pid:858) [plugin] - coc 0.0.78-030aef2f6d initialized with node: v12.16.3

2020-05-02T14:37:43.771 INFO (pid:858) [services] - registered service "rust-analyzer"

2020-05-02T14:37:43.773 INFO (pid:858) [services] - Rust Analyzer Language Server state change: stopped => starting

2020-05-02T14:37:43.816 INFO (pid:858) [language-client-index] - rust-analyzer started with 871

2020-05-02T14:37:43.827 ERROR (pid:858) [language-client-client] - connection error: Error: write EPIPE

    at afterWriteDispatched (internal/stream_base_commons.js:154:25)

    at writeGeneric (internal/stream_base_commons.js:145:3)

    at Socket._writeGeneric (net.js:784:11)

    at Socket._write (net.js:796:8)

    at doWrite (_stream_writable.js:403:12)

    at writeOrBuffer (_stream_writable.js:387:5)

    at Socket.Writable.write (_stream_writable.js:318:11)

    at StreamMessageWriter.write (/home/anouar/.vim/plugged/coc.nvim/build/index.js:17174:27)

    at /home/anouar/.vim/plugged/coc.nvim/build/index.js:16322:35
    at new Promise (<anonymous>) {

  errno: 'EPIPE',

  code: 'EPIPE',

  syscall: 'write'

} undefined

2020-05-02T14:37:43.831 INFO (pid:858) [services] - Rust Analyzer Language Server state change: starting => stopped

2020-05-02T14:37:43.833 ERROR (pid:858) [language-client-client] - connection error: Error 

[ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:399:19)

    at writeOrBuffer (_stream_writable.js:387:5)

    at Socket.Writable.write (_stream_writable.js:318:11)

    at StreamMessageWriter.write (/home/anouar/.vim/plugged/coc.nvim/build/index.js:17176:27)

    at /home/anouar/.vim/plugged/coc.nvim/build/index.js:16322:35

    at new Promise (<anonymous>)

    at Object.sendRequest (/home/anouar/.vim/plugged/coc.nvim/build/index.js:16312:26)

    at Object.initialize (/home/anouar/.vim/plugged/coc.nvim/build/index.js:55240:44)

    at LanguageClient.doInitialize (/home/anouar/.vim/plugged/coc.nvim/build/index.js:57342:27)

    at LanguageClient.initialize (/home/anouar/.vim/plugged/coc.nvim/build/index.js:57338:25) {

  code: 'ERR_STREAM_DESTROYED'

} undefined

2020-05-02T14:37:43.834 ERROR (pid:858) [language-client-client] - connection error: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed

    at doWrite (_stream_writable.js:399:19)

    at writeOrBuffer (_stream_writable.js:387:5)

    at Socket.Writable.write (_stream_writable.js:318:11)

    at StreamMessageWriter.write (/home/anouar/.vim/plugged/coc.nvim/build/index.js:17174:27)

    at /home/anouar/.vim/plugged/coc.nvim/build/index.js:16322:35
    at new Promise (<anonymous>)

    at Object.sendRequest (/home/anouar/.vim/plugged/coc.nvim/build/index.js:16312:26)

    at Object.shutdown (/home/anouar/.vim/plugged/coc.nvim/build/index.js:55241:36)

    at /home/anouar/.vim/plugged/coc.nvim/build/index.js:57434:31 {

  code: 'ERR_STREAM_DESTROYED'

} undefined

2020-05-02T14:37:43.835 ERROR (pid:858) [language-client-client] - connection error: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed

    at doWrite (_stream_writable.js:399:19)

    at writeOrBuffer (_stream_writable.js:387:5)

    at Socket.Writable.write (_stream_writable.js:318:11)

    at StreamMessageWriter.write (/home/anouar/.vim/plugged/coc.nvim/build/index.js:17176:27)

    at /home/anouar/.vim/plugged/coc.nvim/build/index.js:16322:35

    at new Promise (<anonymous>)

    at Object.sendRequest (/home/anouar/.vim/plugged/coc.nvim/build/index.js:16312:26)

    at Object.shutdown (/home/anouar/.vim/plugged/coc.nvim/build/index.js:55241:36)

    at /home/anouar/.vim/plugged/coc.nvim/build/index.js:57434:31 {

  code: 'ERR_STREAM_DESTROYED'

} undefined
```

### CocInfo Output

```versions
vim version: NVIM v0.5.0-dev
node version: v12.16.3
coc.nvim version: 0.0.78-030aef2f6d
term: xterm-256color
platform: linux

## Output channel: Rust Analyzer Language Server Trace


## Output channel: rust-analyzer

[Error  - 2:43:53 PM] Connection to server is erroring. Shutting down server.
[Error  - 2:43:53 PM] Connection to server is erroring. Shutting down server.
[Error  - 2:43:53 PM] Connection to server is erroring. Shutting down server.
/home/anouar/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer: 1: /home/anouar/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer: Syntax error: word unexpected (expecting ")")
[Error  - 2:43:53 PM] /home/anouar/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer exited with code: 2
```

**Comment by anouarkappitou** [comment]
Removing **coc-rust-analyzer-data** and reinstalling rust-analyzer resolves the issue, maybe the first installation was corrupted.
