### ISSUE TITLE
Analyzer stopping

### ISSUE THREAD

**Issue by alok** [fannheyward/coc-rust-analyzer#248]
Not sure if this is the right place to post an issue, but my rust-analyzer keeps stopping when used with coc.

Output of coc's log:

```
2020-05-18T00:40:48.154 INFO (pid:42400) [services] - registered service "languageserver.bash"
2020-05-18T00:40:48.177 INFO (pid:42400) [services] - registered service "rust-analyzer"
2020-05-18T00:40:48.178 INFO (pid:42400) [services] - Rust Analyzer Language Server state change: stopped => starting
2020-05-18T00:40:48.347 INFO (pid:42400) [language-client-index] - Language server "rust-analyzer" started with 42420
2020-05-18T00:40:48.358 ERROR (pid:42400) [language-client-client] - connection error: Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:783:11)
    at Socket._write (net.js:795:8)
    at writeOrBuffer (_stream_writable.js:353:12)
    at Socket.Writable.write (_stream_writable.js:303:12)
    at StreamMessageWriter.write (/Users/alokbeniwal/.config/nvim/bundle/coc.nvim/build/index.js:17199:27)
    at /Users/alokbeniwal/.config/nvim/bundle/coc.nvim/build/index.js:16347:35
    at new Promise (<anonymous>)
    at Object.sendRequest (/Users/alokbeniwal/.config/nvim/bundle/coc.nvim/build/index.js:16337:26) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
} undefined
2020-05-18T00:40:48.359 INFO (pid:42400) [services] - Rust Analyzer Language Server state change: starting => stopped
2020-05-18T00:40:48.364 INFO (pid:42400) [plugin] - coc 0.0.78-0033e4e624 initialized with node: v14.1.0
```
My rust-analyzer is the latest version (31611da).

**Comment by fannheyward** [comment]
Tested with latest nightly release (31611da), can't reproduce your issue. What's your coc.nvim version? Please upgrade coc to latest release.

**Comment by opensourcegeek** [comment]
I see same error as well,

`2020-05-18T21:00:06.442 INFO (pid:58473) [services] - registered service "eslint"
2020-05-18T21:00:06.453 INFO (pid:58473) [services] - registered service "rust-analyzer"
2020-05-18T21:00:06.453 INFO (pid:58473) [services] - Rust Analyzer Language Server state change: stopped => starting
2020-05-18T21:00:06.631 INFO (pid:58473) [plugin] - coc 0.0.78-89c0c2380b initialized with node: v12.11.1
2020-05-18T21:00:06.634 INFO (pid:58473) [language-client-index] - rust-analyzer started with 58488
2020-05-18T21:00:06.637 ERROR (pid:58473) [language-client-client] - connection error: Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:150:25)
    at writeGeneric (internal/stream_base_commons.js:141:3)
    at Socket._writeGeneric (net.js:768:11)
    at Socket._write (net.js:780:8)
    at doWrite (_stream_writable.js:431:12)
    at writeOrBuffer (_stream_writable.js:415:5)
    at Socket.Writable.write (_stream_writable.js:305:11)
    at StreamMessageWriter.write (/home/opensourcegeek/.config/nvim/plugged/coc.nvim/build/index.js:17046:27)
    at /home/opensourcegeek/.config/nvim/plugged/coc.nvim/build/index.js:16193:35
    at new Promise (<anonymous>) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
} undefined
`
vim version: NVIM v0.4.3
node version: v12.11.1
coc.nvim version: 0.0.78-89c0c2380b
term: screen-256color
platform: linux

I believe that's the latest version of coc-nvim?

**Comment by alok** [comment]
I'm using the latest coc.nvim, built from master.

**Comment by fannheyward** [comment]
@opensourcegeek your coc.nvim is not the latest.

@alok does tested with latest master, still can't reproduce this issue.

**Comment by alok** [comment]
If I explictly set `  "rust-analyzer.serverPath": "rust-analyzer"`, it fixes the issue. Trying to run the downloaded rust-analyzer executable immediately exits with

`[1]    23029 killed     ~/.config/coc/extensions/coc-rust-analyzer-data/rust-analyze`

**Comment by opensourcegeek** [comment]
@fannheyward I did a plug upgrade and that's the version I ended up with. Let me check if that's from master. What version are you running please? I will try and align the versions based off yours.

**Comment by sezna** [comment]
This happened to me as well on the latest version of rust-analyzer. Weirdly, adding `"rust-analyzer.serverPath": "rust-analyzer"` itself did not fix the issue, but after trying it out and reverting it, the issue was fixed.

**Comment by fannheyward** [comment]
@opensourcegeek latest coc.nvim master branch.

@alok does `~/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer --help` works? What's your OS platform?

**Comment by alok** [comment]
macOS 10.14.6

`[1]    70508 killed
~/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer --help`

--- Alok

**Comment by fannheyward** [comment]
@alok delete `~/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer` and try to download again. Looks like the binary is broken.

**Comment by fannheyward** [comment]
@alok I think I've found this issue, you need to allow `rust-analyzer` to run in System Settings - Security and Privacy.

**Comment by matclab** [comment]
> @alok delete `~/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer` and try to download again. Looks like the binary is broken.

It worked for me. Thanks !

**Comment by opensourcegeek** [comment]
@fannheyward Thanks - building coc.nvim from source (master) fixes the issue.

**Comment by SOF3** [comment]
> `~/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer --help` 

this gives me `version GLIBC_2.25 not found`. I am using a slightly old version of Debian 9. Any suggestions on that?

**Comment by fannheyward** [comment]
It's rust-analyzer's issue.

**Comment by SOF3** [comment]
> It's rust-analyzer's issue.

But it's coc-rust-analyzer downloading the wrong binary? If I do `rustup +nightly component add rust-analyzer-preview`, the binary in rustup works.
