### ISSUE TITLE
TypeError appears to break completion and code navigation

### ISSUE THREAD

**Issue by erichgess** [fannheyward/coc-rust-analyzer#279]
Code completion and navigation tools, such as go to defintion, are no longer working.  The Coc logs show the coc-rust-analyzer failing with this error message: `Error on load extension coc-rust-analyzer from ~/.../coc-rust-analyzer/lib/index.js: TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function`.

According to `:CocList extension` I have version 0.7.2 of the coc-rust-analyzer and I have the latest nightly build of rust-analyzer installed.  Using Vim 8.2.

Here is the stack trace from `CocOpenLog`:

```
2020-06-09T15:29:30.160 INFO (pid:11372) [plugin] - coc 0.0.78-fd9e7d3972 initialized with node: v8.17.0
2020-06-09T15:29:33.405 ERROR (pid:11372) [extensions] - TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at Object.promisify (internal/util.js:214:11)
    at Object.<anonymous> (/home/erich/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:6436:33)
    at __webpack_require__ (/home/erich/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:20:30)
    at Object.<anonymous> (/home/erich/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:5782:22)
    at __webpack_require__ (/home/erich/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:20:30)
    at Object.<anonymous> (/home/erich/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:225:15)
    at __webpack_require__ (/home/erich/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:20:30)
    at Object.<anonymous> (/home/erich/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:116:27)
    at __webpack_require__ (/home/erich/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:20:30)
    at Object.create.k2 (/home/erich/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:84:18)
```

**Comment by fannheyward** [comment]
Same issue #266, you're using node 8.0, please upgrade to node 10+ https://github.com/neoclide/coc.nvim#quick-start
