### ISSUE TITLE
Connection error to rust_analyzer

### ISSUE THREAD

**Issue by traxys** [fannheyward/coc-rust-analyzer#349]
I don't know if this is the best place to report this issue, as this could have been caused solely by CoC, or even a mistake on my part.

My completion broke a few days ago, so I checked here to see if this was a known issue, the only one I could find was with an `EPERM`, but when I run `:CocOpenLog` I get another error:
```
2020-08-12T14:07:13.192 INFO (pid:3382) [services] - registered service "rust-analyzer"
2020-08-12T14:07:13.193 INFO (pid:3382) [services] - Rust Analyzer Language Server state change: stopped => starting
2020-08-12T14:07:13.199 INFO (pid:3382) [language-client-index] - Language server "rust-analyzer" started with 3410
2020-08-12T14:07:13.206 ERROR (pid:3382) [language-client-client] - connection error: Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:785:11)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (_stream_writable.js:352:12)
    at Socket.Writable.write (_stream_writable.js:303:10)
    at StreamMessageWriter.write (/home/traxys/.local/share/nvim/plugged/coc.nvim/build/index.js:18129:27)
    at /home/traxys/.local/share/nvim/plugged/coc.nvim/build/index.js:17277:35
    at new Promise (<anonymous>)
    at Object.sendRequest (/home/traxys/.local/share/nvim/plugged/coc.nvim/build/index.js:17267:26) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
} undefined
2020-08-12T14:07:13.223 INFO (pid:3382) [services] - Rust Analyzer Language Server state change: starting => stopped
2020-08-12T14:07:13.430 WARN (pid:3382) [attach] - Plugin not ready when received "highlight" []
2020-08-12T14:07:14.173 WARN (pid:3382) [extensions] - Extension coc-rust-analyzer activate cost more than 1s
2020-08-12T14:07:14.176 INFO (pid:3382) [plugin] - coc.nvim 0.0.78-bdd9a9e140 initialized with node: v14.7.0 after 1157ms
```

I tried using `CoC` on another file, namely a `JS` file and this worked, so it is a `Rust` specific problem

**Comment by fannheyward** [comment]
Looks like your `rust-analyzer` is broken, try to delete `~/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer` and try again.

**Comment by traxys** [comment]
Yup that fixes it ! Could you add this on the README somewhere (or is it specified in the CoC readme and I did not see it) ? I thought it was probably a broken rust analyzer as I was pretty sure I broke a download, but I had no idea where the data was stored

**Comment by traxys** [comment]
Thank you very much!

**Comment by lilhammer111** [comment]
另外，我也遇到client连接不上的问题了，因为我使用snap 安装的rustup。
两个建议大概率可以解决这个问题：
1. 确保rust-analyzer的执行路径在环境变量中（即使我使用了snap安装rustup，也成功连接了），一定要手动加，不要因为可以直接调用rust toolchains里的工具就以为rust-analyzer在环境变量里了
2. 使用官网的方式安装rustup，然后再rustup component add 这两个rust-analyzer（和rust-src）这两个tool。

**Comment by towry** [comment]
My debug steps of this issue is:

1. run `rust-analyzer --version`, print: `error: 'rust-analyzer' is not installed for the toolchain 'nightly-x86_64-apple-darwin'`
2. run `rustup component add rust-analyzer` to install the correct version.

problem solved.

**Comment by RyanNicoletti** [comment]
> My debug steps of this issue is:
> 
> 1. run `rust-analyzer --version`, print: `error: 'rust-analyzer' is not installed for the toolchain 'nightly-x86_64-apple-darwin'`
> 2. run `rustup component add rust-analyzer` to install the correct version.
> 
> problem solved.

Thanks a lot for this, only thing that finally fixed it for me. Seems obvious in hind sight

**Comment by StEvUgnIn** [comment]
> Looks like your `rust-analyzer` is broken, try to delete `~/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer` and try again.

Where is this directory on Windows 11? I checked the home path, and it is not there.

**Comment by StEvUgnIn** [comment]
I had to change the following line in settings.json (User) and set the following key to the path of `rust-analyzer`:

```json
{
"rust-analyzer.server.path": "rust-analyzer.exe",
}
```
