### ISSUE TITLE
rust-analyzer.run gives error “Invalid channel id” 

### ISSUE THREAD

**Issue by wolverian** [fannheyward/coc-rust-analyzer#361]
Here’s the `CocOpenLog` output:

```
2020-08-27T07:56:04.463 INFO (pid:289844) [services] - registered service "rust-analyzer"
2020-08-27T07:56:04.465 INFO (pid:289844) [services] - Rust Analyzer Language Server state change: stopped => starting
2020-08-27T07:56:04.469 INFO (pid:289844) [language-client-index] - Language server "rust-analyzer" started with 289862
2020-08-27T07:56:04.478 INFO (pid:289844) [services] - Rust Analyzer Language Server state change: starting => running
2020-08-27T07:56:04.490 INFO (pid:289844) [services] - service rust-analyzer started
2020-08-27T07:56:04.503 INFO (pid:289844) [plugin] - coc.nvim 0.0.78-9f9d8a32c4 initialized with node: v10.19.0 after 284ms
2020-08-27T07:56:11.051 ERROR (pid:289844) [server] - unhandledRejection  Promise {
  <rejected> Error: request error nvim_call_function - Vim(return):E900: Invalid channel id
      at transport.request (/home/ubuntu/.vim/plugged/coc.nvim/build/index.js:15216:32)
      at pending.set (/home/ubuntu/.vim/plugged/coc.nvim/build/index.js:11881:13)
      at NvimTransport.parseMessage (/home/ubuntu/.vim/plugged/coc.nvim/build/index.js:11822:17)
      at DecodeStream.NvimTransport.decodeStream.on (/home/ubuntu/.vim/plugged/coc.nvim/build/index.js:11792:18)
      at DecodeStream.emit (events.js:198:13)
      at addChunk (_stream_readable.js:288:12)
      at readableAddChunk (_stream_readable.js:269:11)
      at DecodeStream.Readable.push (_stream_readable.js:224:10)
      at DecodeStream.Transform.push (_stream_transform.js:151:32)
      at DecodeBuffer.DecodeStream.decoder.push (/home/ubuntu/.vim/plugged/coc.nvim/build/index.js:14764:12) } Error: request error nvim_call_function - Vim(return):E900: Invalid channel id
    at transport.request (/home/ubuntu/.vim/plugged/coc.nvim/build/index.js:15216:32)
    at pending.set (/home/ubuntu/.vim/plugged/coc.nvim/build/index.js:11881:13)
    at NvimTransport.parseMessage (/home/ubuntu/.vim/plugged/coc.nvim/build/index.js:11822:17)
    at DecodeStream.NvimTransport.decodeStream.on (/home/ubuntu/.vim/plugged/coc.nvim/build/index.js:11792:18)
    at DecodeStream.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at DecodeStream.Readable.push (_stream_readable.js:224:10)
    at DecodeStream.Transform.push (_stream_transform.js:151:32)
    at DecodeBuffer.DecodeStream.decoder.push (/home/ubuntu/.vim/plugged/coc.nvim/build/index.js:14764:12)

**Comment by wolverian** [comment]
And here’s `CocInfo`:

```
## versions
                                                                   
vim version: NVIM v0.4.3
node version: v10.19.0
coc.nvim version: 0.0.78-9f9d8a32c4
coc.nvim directory: /home/ubuntu/.vim/plugged/coc.nvim                                                                     
term: xterm-256color
platform: linux
                                                                   
## Output channel: Rust Analyzer Language Server Trace

**Comment by wolverian** [comment]
This is on Ubuntu 20.04, arm64.

**Comment by fannheyward** [comment]
What's your rust-analyzer version?

Try `:CocCommand rust-analyzer.serverVersion`

**Comment by wolverian** [comment]
@fannheyward Sorry I didn’t include that in the report. I’m using latest `stable` installed with `rustup`: `[coc.nvim] rust-analyzer ed09bd3`.

**Comment by wolverian** [comment]
I checked with the latest nightly rust-analyzer with the same result. I also updated Node to v12, again with no change to the error.

**Comment by wolverian** [comment]
I suspect this could be related to the fact I’m running on ARM. I can provide access to an ARM EC2 instance for testing if that’s required.

**Comment by fannheyward** [comment]
Can you test your case with VSCode + rust-analyzer? Lets make sure that rust-analyzer can handle it.
