### ISSUE TITLE
Cargo watch throws errors

### ISSUE THREAD

**Issue by JeanMertz** [fannheyward/coc-rust-analyzer#4]
After upgrading to the latest version, and starting cargo-watch, I got the following error:

```
[coc.nvim] Command: codeAction not found
[coc.nvim] error: { Error: Connection is disposed.
    at throwIfClosedOrDisposed (/Users/jean/.config/nvim/plugged/coc.nvim/build/index.js:38379:19)
    at Object.sendNotification (/Users/jean/.config/nvim/plugged/coc.nvim/build/index.js:38426:13)
    at token.onCancellationRequested (/Users/jean/.config/nvim/plugged/coc.nvim/build/index.js:38538:32)
    at CallbackList.invoke (/Users/jean/.config/nvim/plugged/coc.nvim/build/index.js:39233:39)
    at Emitter.fire (/Users/jean/.config/nvim/plugged/coc.nvim/build/index.js:39291:36)
    at MutableToken.cancel (/Users/jean/.config/nvim/plugged/coc.nvim/build/index.js:39549:31)
    at CancellationTokenSource.cancel (/Users/jean/.config/nvim/plugged/coc.nvim/build/index.js:39590:25)
    at Handler.triggerSignatureHelp (/Users/jean/.config/nvim/plugged/coc.nvim/build/index.js:86437:39)
    at Handler.events_1.default.on (/Users/jean/.config/nvim/plugged/coc.nvim/build/index.js:85792:32)
    at processTicksAndRejections (internal/process/next_tick.js:81:5) code: 2 }
```

Don't really have a minimal reproducible example, as it happened while working in a bigger work-related project.

**Comment by fannheyward** [comment]
VSCode will exec `vscode.executeCodeActionProvider` if cargo watch finds a fix. In vim, the fix codeAction will only push to action lists, then `<Plug>(coc-codeaction)` to apply.

**Comment by JeanMertz** [comment]
Thanks for the fix. So if I understand correctly, this plugin can't/won't auto-apply a fix? I'm not saying I would want it to (I'm not sure actually), but just making sure.

**Comment by fannheyward** [comment]
In fact, the extension indeed can do auto-fix with `applySourceChange`, and I already implemented it, but in my test, (using rust-analyzer codebase), auto-fix not works perfectly:

1. edit to make an error
2. save
3. cargo check to find error, showing with diagnostics
4. at the same time, auto-fix the error
5. but diagnostics still showing, you need to save to notify cargo check again

So, I didn't make auto-fix works default, in fact, I also not sure whether auto-fix really needed. In my workflow, I mapped `ga` to `<Plug>(coc-codeaction)`, every time the diagnostic error shows, I just `ga` to find whether a fix available.

**Comment by JeanMertz** [comment]
Yeah, that makes total sense. I'm going to map `<Plug>(coc-codeaction)` as well, and see how that goes. Great work so far, keep it up 🚀
