### ISSUE TITLE
CocAction breaks when using git dependency 

### ISSUE THREAD

**Issue by beemdvp** [fannheyward/coc-rust-analyzer#405]
Hi all,
Lets say im using an unreleased crate using master branch
```
lambda_http = { git = "https://github.com/awslabs/aws-lambda-rust-runtime.git", branch = "master" }
```
This completely breaks coc-action with the following log:
```
2020-10-06T22:54:29.528 ERROR (pid:110118) [attach] - Notification error: codeAction [ '' ] ResponseError: canceled by client
    at handleResponse (/home/beem/.vim/plugged/coc.nvim/build/index.js:17144:48)
    at processMessageQueue (/home/beem/.vim/plugged/coc.nvim/build/index.js:16971:17)
    at Immediate.<anonymous> (/home/beem/.vim/plugged/coc.nvim/build/index.js:16955:13)
    at processImmediate (internal/timers.js:456:21) {
  code: -32800,
  data: undefined
}
```
This problem goes away when I use a published crate for `lambda_http`

Any help would be much appreciated and thanks again for developing this for coc! :)

**Comment by beemdvp** [comment]
Closing as this has been fixed in latest master https://github.com/rust-analyzer/rust-analyzer/pull/6161
