### ISSUE TITLE
typing unwrap() freezes neovim 

### ISSUE THREAD

**Issue by hur** [fannheyward/coc-rust-analyzer#504]
Typing `Some(1).unwrap()` (namely, the character `(` being typed) causes neovim to freeze for ~5 seconds.

System Info: 
NVIM v0.4.3 Release
coc.nvim version: 0.0.79-c7c24f61f4
coc-rust-analyzer 0.21.0
auto-pairs installed with `vim-plug`
rust-analyzer a0fa522 (from :CocCommand rust-analyzer.serverVersion)

EDIT: Not sure anymore that it is due to precisely auto-pairs right now, it actually seems to appear regardless.

**Comment by fannheyward** [comment]
Disable `auto-pairs` and try again.

**Comment by the-shank** [comment]
I can confirm this is happening to me too:

System Info:
Operating System: Manjaro
NVIM v0.4.4

`:CocInfo` output
```
undefined## versions

vim version: NVIM v0.4.4
node version: v15.3.0
coc.nvim version: 0.0.79-9245f3a08c
coc.nvim directory: /home/shank/.config/nvim/plugged/coc.nvim
term: tmux-256color
platform: linux

## Log of coc.nvim
2020-12-11T11:24:58.134 INFO (pid:37877) [services] - registered service "languageserver.golang"
2020-12-11T11:24:58.324 INFO (pid:37877) [plugin] - coc.nvim 0.0.79-9245f3a08c initialized with node: v15.3.0 after 283ms
2020-12-11T11:25:00.697 INFO (pid:37877) [services] - registered service "rust-analyzer"
2020-12-11T11:25:00.697 INFO (pid:37877) [services] - Rust Analyzer Language Server state change: stopped => starting
2020-12-11T11:25:00.724 INFO (pid:37877) [language-client-index] - Language server "rust-analyzer" started with 37953
2020-12-11T11:25:00.749 INFO (pid:37877) [services] - Rust Analyzer Language Server state change: starting => running
2020-12-11T11:25:00.766 INFO (pid:37877) [services] - service rust-analyzer started
2020-12-11T11:25:08.206 INFO (pid:37877) [completion-complete] - Results from: rust-analyzer-1
2020-12-11T11:25:11.530 INFO (pid:37877) [willSaveHandler] - Will save cost: 161
2020-12-11T11:25:32.349 INFO (pid:37877) [completion-complete] - Results from: around,rust-analyzer-1
2020-12-11T11:25:33.839 INFO (pid:37877) [completion-complete] - Results from: rust-analyzer-1
2020-12-11T11:25:37.238 WARN (pid:37877) [events] - Handler of TextChangedI blocked more than 2s: Error
    at Events.on (/home/shank/.config/nvim/plugged/coc.nvim/build/index.js:16593:25)
    at new Handler (/home/shank/.config/nvim/plugged/coc.nvim/build/index.js:94057:26)
    at Plugin.init (/home/shank/.config/nvim/plugged/coc.nvim/build/index.js:23994:28)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async /home/shank/.config/nvim/plugged/coc.nvim/build/index.js:11641:13
2020-12-11T11:25:43.187 ERROR (pid:37877) [model-float] - Error on create popup: Cannot read property 'dispose' of null
2020-12-11T11:25:52.477 INFO (pid:37877) [willSaveHandler] - Will save cost: 164
```

**Comment by GopherJ** [comment]
@the-shank maybe you can show what this line is:

```
~/.config/nvim/plugged/coc.nvim/build/index.js:16593
```

**Comment by the-shank** [comment]
@hur can you check your `:CocInfo` to see if there are any errors reported, like me.

**Comment by GopherJ** [comment]
maybe it's because this call:

https://github.com/neoclide/coc.nvim/blob/master/src/events.ts#L121

took more than 2 seconds to finish so the error happens

**Comment by the-shank** [comment]
yeah but this only happens upon entering `(` pertaining to `option(`. Except this everything works fine, without and sort of delay or unresponsiveness.

**Comment by hur** [comment]
Here's my CocInfo output:
```
## versions

vim version: NVIM v0.4.3
node version: v14.15.1
coc.nvim version: 0.0.79-c7c24f61f4
coc.nvim directory: /home/atte/.vim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2020-12-11T10:39:53.843 INFO (pid:888233) [plugin] - coc.nvim 0.0.79-c7c24f61f4 initialized with node: v14.15.1 after 55ms
2020-12-11T10:39:55.812 INFO (pid:888233) [services] - registered service "rust-analyzer"
2020-12-11T10:39:55.813 INFO (pid:888233) [services] - Rust Analyzer Language Server state change: stopped => starting
2020-12-11T10:39:55.828 INFO (pid:888233) [language-client-index] - Language server "rust-analyzer" started with 889329
2020-12-11T10:39:55.838 INFO (pid:888233) [services] - Rust Analyzer Language Server state change: starting => running
2020-12-11T10:39:55.846 INFO (pid:888233) [services] - service rust-analyzer started
2020-12-11T10:40:00.231 INFO (pid:888233) [willSaveHandler] - Will save cost: 62
2020-12-11T10:40:07.996 INFO (pid:888233) [completion-complete] - Results from: rust-analyzer-1
2020-12-11T10:40:09.238 INFO (pid:888233) [completion-complete] - Results from: rust-analyzer-1
2020-12-11T10:40:11.123 INFO (pid:888233) [completion-complete] - Results from: rust-analyzer-1
2020-12-11T10:40:14.856 WARN (pid:888233) [events] - Handler of TextChangedI blocked more than 2s: Error
    at Events.on (/home/atte/.vim/plugged/coc.nvim/build/index.js:16589:25)
    at new Signature (/home/atte/.vim/plugged/coc.nvim/build/index.js:97321:26)
    at new Handler (/home/atte/.vim/plugged/coc.nvim/build/index.js:94378:26)
    at Plugin.init (/home/atte/.vim/plugged/coc.nvim/build/index.js:23990:28)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /home/atte/.vim/plugged/coc.nvim/build/index.js:11641:13


```
Looks like the same error as @the-shank is receiving.

**Comment by fannheyward** [comment]
Try minimal vimrc, only coc and coc-rust-analyzer. I still can't reproduce it.

**Comment by hur** [comment]
Removed all other coc-extensions and emptied my `init.vim`. In `.config/neovim/init.vim` I have: 
``` 
call plug#begin('~/.vim/plugged')
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
```
Issue still persists.

**Comment by the-shank** [comment]
@fannheyward which OS are you on?

**Comment by GopherJ** [comment]
not sure if it helps, but maybe you can try to use `coc-pairs`, I didn't have such kind of issue while using `coc-pairs`, I sometimes got neovim freezes but that's due to RA's memory usage or something else

**Comment by hur** [comment]
> not sure if it helps, but maybe you can try to use `coc-pairs`, I didn't have such kind of issue while using `coc-pairs`, I sometimes got neovim freezes but that's due to RA's memory usage or something else

This didn't help. 

I'm on Ubuntu 20.04.1

**Comment by fannheyward** [comment]
> @fannheyward which OS are you on?

macOS

**Comment by the-shank** [comment]
@hur and I are both on linux. @GopherJ if you are on linux, can you please try if you are able to reproduce it.

**Comment by GopherJ** [comment]
@the-shank  I'm no linux and I tried already but I'm not able to reproduce it.

**Comment by the-shank** [comment]
> @the-shank  I'm on linux and I tried already but I'm not able to reproduce it. My configs are all online if you would to compare: https://github.com/GopherJ/cfg/tree/master/coc

Thank u, will try and report back. If u dont mind, can you share the output of your `:CocInfo`.

**Comment by GopherJ** [comment]
@the-shank sure no pb.

![image](https://user-images.githubusercontent.com/33961674/102018058-0df6b880-3d6b-11eb-9929-d6a0b4f460ae.png)

**Comment by the-shank** [comment]
@GopherJ thanks for sharing the CocInfo. I just tried the 0.5.0-dev version of nvim and this issue is not reproducible there. I see that @hur and me are both on 0.4.x version of nvim.

I guess I will just switch to 0.5.0-dev version for now. Thank you for your help!

**Comment by the-shank** [comment]
@hur can you try if you can reproduce the issue with 0.5.0-dev version?

**Comment by hur** [comment]
@the-shank works fine in nvim 0.5.x.I guess I'll switch to that as well.
