### ISSUE TITLE
feature.dispose is not a function when opening rust files

### ISSUE THREAD

**Issue by sezna** [fannheyward/coc-rust-analyzer#508]
Hi,

This morning I upgraded neovim to version 5 and coc to the latest release version. I then re-installed `coc-rust-analyzer` from the latest release.

Whenever I open any `.rs` file, I get this error:
```
[coc.nvim]: TypeError: feature.dispose is not a function
    at LanguageClient.cleanUp (/home/alex/.vim/plugs/coc.nvim/build/index.js:82483:21)
    at LanguageClient.stop (/home/alex/.vim/plugs/coc.nvim/build/index.js:82452:14)
    at LanguageClient.stop (/home/alex/.vim/plugs/coc.nvim/build/index.js:79717:22)
    at LanguageClient.handleConnectionError (/home/alex/.vim/plugs/coc.nvim/build/index.js:82625:18)
    at errorHandler (/home/alex/.vim/plugs/coc.nvim/build/index.js:82573:18)
    at /home/alex/.vim/plugs/coc.nvim/build/index.js:80200:9
    at CallbackList.invoke (/home/alex/.vim/plugs/coc.nvim/build/index.js:18265:39)
    at Emitter.fire (/home/alex/.vim/plugs/coc.nvim/build/index.js:18324:36)
    at writeErrorHandler (/home/alex/.vim/plugs/coc.nvim/build/index.js:16969:22)
    at CallbackList.invoke (/home/alex/.vim/plugs/coc.nvim/build/index.js:18265:39)
    at Emitter.fire (/home/alex/.vim/plugs/coc.nvim/build/index.js:18324:36)
    at StreamMessageWriter.fireError (/home/alex/.vim/plugs/coc.nvim/build/index.js:18375:27)
    at Socket.<anonymous> (/home/alex/.vim/plugs/coc.nvim/build/index.js:18399:51)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
```

This doesn't seem to happen with other filetypes, so I think it is related to coc-rust-analyzer. Is there something I'm using that is out of date?

Thanks,
Alex

**Comment by sezna** [comment]
I should also mention my versions:
Node: I tried 14 and 15
neovim: v0.5
coc.nvim version: 0.0.79-721f227aa0

Log:
```
 11
 12 2020-12-11T20:20:45.363 INFO (pid:23223) [services] - registered service "rust-analyzer"
 13 2020-12-11T20:20:45.364 INFO (pid:23223) [services] - Rust Analyzer Language Server state change: stop
 14 2020-12-11T20:20:45.370 INFO (pid:23223) [language-client-index] - Language server "rust-analyzer" sta
 15 2020-12-11T20:20:45.374 ERROR (pid:23223) [language-client-client] - connection error: Error: write EP
 16     at afterWriteDispatched (internal/stream_base_commons.js:154:25)
 17     at writeGeneric (internal/stream_base_commons.js:145:3)
 18     at Socket._writeGeneric (net.js:782:11)
 19     at Socket._write (net.js:794:8)
 20     at writeOrBuffer (_stream_writable.js:352:12)
 21     at Socket.Writable.write (_stream_writable.js:303:10)
 22     at StreamMessageWriter.write (/home/alex/.vim/plugs/coc.nvim/build/index.js:18411:27)
 23     at /home/alex/.vim/plugs/coc.nvim/build/index.js:17559:35
 24     at new Promise (<anonymous>)
 25     at Object.sendRequest (/home/alex/.vim/plugs/coc.nvim/build/index.js:17549:26)
 26     at Object.initialize (/home/alex/.vim/plugs/coc.nvim/build/index.js:80226:44)
 27     at LanguageClient.doInitialize (/home/alex/.vim/plugs/coc.nvim/build/index.js:82363:27)
 28     at LanguageClient.initialize (/home/alex/.vim/plugs/coc.nvim/build/index.js:82359:25)
 29     at /home/alex/.vim/plugs/coc.nvim/build/index.js:82283:25 {
 30   errno: -32,
 31   code: 'EPIPE',
 32   syscall: 'write'
 33 } undefined
 34 2020-12-11T20:20:45.388 INFO (pid:23223) [services] - Rust Analyzer Language Server state change: star
 35 2020-12-11T20:20:46.342 WARN (pid:23223) [extensions] - Extension coc-rust-analyzer activate cost more
 36 2020-12-11T20:20:46.347 INFO (pid:23223) [plugin] - coc.nvim 0.0.79-721f227aa0 initialized with node:
 37
```

**Comment by chemzqm** [comment]
`StaticFeature` need to have `dispose()` function now, which can be empty.

Will check it on coc.nvim.

**Comment by fannheyward** [comment]
https://github.com/neoclide/coc.nvim/commit/ea17609a24c74f0dad837b3a9dba38bcf8f006a3

**Comment by sezna** [comment]
This seems to have fixed it, thanks!

**Comment by sezna** [comment]
Although now there are new errors when using the latest coc with rust analyzer...

```
  1 2020-12-12T19:59:11.049 INFO (pid:16387) [services] - registered service "rust-analyzer"
  2 2020-12-12T19:59:11.050 INFO (pid:16387) [services] - Rust Analyzer Language Server state change: stopped => starting
  3 2020-12-12T19:59:11.057 INFO (pid:16387) [language-client-index] - Language server "rust-analyzer" started with 16400
  4 2020-12-12T19:59:11.060 ERROR (pid:16387) [language-client-client] - connection error: Error: write EPIPE
  5     at afterWriteDispatched (internal/stream_base_commons.js:154:25)
  6     at writeGeneric (internal/stream_base_commons.js:145:3)
  7     at Socket._writeGeneric (net.js:782:11)
  8     at Socket._write (net.js:794:8)
  9     at writeOrBuffer (_stream_writable.js:352:12)
 10     at Socket.Writable.write (_stream_writable.js:303:10)
 11     at StreamMessageWriter.write (/home/alex/.vim/plugs/coc.nvim/build/index.js:18411:27)
 12     at /home/alex/.vim/plugs/coc.nvim/build/index.js:17559:35
 13     at new Promise (<anonymous>)
 14     at Object.sendRequest (/home/alex/.vim/plugs/coc.nvim/build/index.js:17549:26)
 15     at Object.initialize (/home/alex/.vim/plugs/coc.nvim/build/index.js:80182:44)
 16     at LanguageClient.doInitialize (/home/alex/.vim/plugs/coc.nvim/build/index.js:82320:27)
 17     at LanguageClient.initialize (/home/alex/.vim/plugs/coc.nvim/build/index.js:82316:25)
 18     at /home/alex/.vim/plugs/coc.nvim/build/index.js:82239:25 {
 19   errno: -32,
 20   code: 'EPIPE',
 21   syscall: 'write'
 22 } undefined
 23 2020-12-12T19:59:11.075 INFO (pid:16387) [services] - Rust Analyzer Language Server state change: starting => stopped
 24 2020-12-12T19:59:11.075 ERROR (pid:16387) [language-client-client] - Feature can't be disposed ExperimentalFeatures {}
 25 2020-12-12T19:59:12.029 WARN (pid:16387) [extensions] - Extension coc-rust-analyzer activate cost more than 1s
 26 2020-12-12T19:59:12.031 INFO (pid:16387) [plugin] - coc.nvim 0.0.79-f2afd214ba initialized with node: v14.4.0 after 1040ms
 27 2020-12-12T19:59:12.994 ERROR (pid:16387) [commands] - TypeError: Cannot read property 'sendRequest' of undefined
 28     at /home/alex/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:210:38
 29     at processTicksAndRejections (internal/process/task_queues.js:97:5)
 30     at async Handler.runCommand (/home/alex/.vim/plugs/coc.nvim/build/index.js:94854:23)
 31     at async Plugin.cocAction (/home/alex/.vim/plugs/coc.nvim/build/index.js:24034:16)
 32     at async NeovimClient.<anonymous> (/home/alex/.vim/plugs/coc.nvim/build/index.js:11597:21)
 33 2020-12-12T19:59:35.452 ERROR (pid:16387) [commands] - TypeError: Cannot read property 'stop' of undefined
 34     at Ctx.checkUpdate (/home/alex/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:6061:31)
 35     at async /home/alex/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:543:9
 36     at async Handler.runCommand (/home/alex/.vim/plugs/coc.nvim/build/index.js:94854:23)
 37     at async Plugin.cocAction (/home/alex/.vim/plugs/coc.nvim/build/index.js:24034:16)
 38     at async NeovimClient.<anonymous> (/home/alex/.vim/plugs/coc.nvim/build/index.js:11597:21)
~
```
