### ISSUE TITLE
Error while opening file

### ISSUE THREAD

**Issue by wojciechkepka** [fannheyward/coc-rust-analyzer#62]
Hi,
I'm trying to use coc-rust-analyzer but I get this error message in vim:

```
[coc.nvim] Error on active extension coc-rust-analyzer: TypeError: Cannot read property 'uri' of null                                                                                                 
    at Function.prepare (/home/wojtek/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:289:50)                                                                                      
    at Object.activate (/home/wojtek/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:106:33)                                                                                       
    at Object.activate (/home/wojtek/.config/nvim/plugged/coc.nvim/build/index.js:36128:57)                                                                                                           
    at Extensions.activate (/home/wojtek/.config/nvim/plugged/coc.nvim/build/index.js:35853:19)                                                                                                       
    at active (/home/wojtek/.config/nvim/plugged/coc.nvim/build/index.js:36033:18)                                                                                                                    
    at Extensions.setupActiveEvents (/home/wojtek/.config/nvim/plugged/coc.nvim/build/index.js:36042:21)                                                                                              
    at Extensions.createExtension (/home/wojtek/.config/nvim/plugged/coc.nvim/build/index.js:36197:18)                                                                                                
    at Extensions.loadExtension (/home/wojtek/.config/nvim/plugged/coc.nvim/build/index.js:35803:18)
```

**Comment by fannheyward** [comment]
Fixed, `CocUpdate` to upgrade coc-rust-analyzer.
