### ISSUE TITLE
Fail to install because of `https`

### ISSUE THREAD

**Issue by PeterlitsZo** [fannheyward/coc-rust-analyzer#751]
I try to install CRA for neovim, but it raise an error like:
```
[coc.nvim] Download rust-analyzer failed, you can get it from https://github.com/rust-analyzer/rust-analyzer
```

There is the output of `:CocOpenLog`:
```
2021-05-26T00:23:27.419 INFO (pid:415980) [plugin] - coc.nvim 0.0.80-998c7d8034 initialized with node: v15.14.0 after 1065ms
2021-05-26T00:23:28.728 ERROR (pid:415980) [extension:coc-rust-analyzer] - TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
    at new NodeError (node:internal/errors:329:5)
    at new ClientRequest (node:_http_client:171:11)
    at request (node:https:333:10)
    at /home/peterlits/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:7854:17
    at new Promise (<anonymous>)
    at fetch (/home/peterlits/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:7830:10)
    at getLatestRelease (/home/peterlits/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:8056:26)
    at Object.activate (/home/peterlits/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js:9046:30)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Object.activate (/home/peterlits/.config/nvim/plugged/coc.nvim/build/index.js:223:1305) {
  code: 'ERR_INVALID_PROTOCOL'
}
2021-05-26T00:23:38.136 INFO (pid:415980) [attach] - receive notification: highlight []
2021-05-26T00:23:42.115 INFO (pid:415980) [attach] - receive request: CocAutocmd [ 'BufWritePre', 1 ]
2021-05-26T00:23:46.163 INFO (pid:415980) [attach] - receive notification: highlight []
2021-05-26T00:24:00.806 INFO (pid:415980) [attach] - receive notification: openLog []
```

It tell me that `https` is not supported. Do I need to install something in node.js or something else?

**Comment by fannheyward** [comment]
Can't reproduce, do you have any proxy setup? Try to upgrade your Node.js to v16 and try again.

**Comment by PeterlitsZo** [comment]
Yes I have a proxy.
I try:
 - Close my proxy. Retry. => Download rust-analyzer failed...
 - `nvm use v16`. Retry. => Download rust-analyzer failed...
 - Reopen my proxy. Retry. => Download rust-analyzer failed...

**Comment by fannheyward** [comment]
Does your proxy support `https`? Is it a `http` only proxy?

**Comment by PeterlitsZo** [comment]
> Does your proxy support `https`? Is it a `http` only proxy?

I think the answer is yes... The google's website is running under https, and I can access it.

**Comment by PeterlitsZo** [comment]
I remember the download program once have run when I first `:CocInstall <the name of this package>`, but then I quit the vim editor quickly.

**Comment by fannheyward** [comment]
You can install rust-analyzer manually, set it by `rust-analyzer.server.path` in your coc-settings.json

**Comment by PeterlitsZo** [comment]
> You can install rust-analyzer manually, set it by `rust-analyzer.server.path` in your coc-settings.json

I had tried before... Now I retry and this is my `:CocConfig`:
```
{
    "rust-analyzer.server.path": "~/.local/bin/rust-analyzer"
}
```

This is the error:
```
2021-05-29T11:17:32.966 INFO (pid:166672) [services] - registered service "rust-analyzer"
2021-05-29T11:17:32.968 INFO (pid:166672) [services] - Rust Analyzer Language Server state change: stopped => starting
2021-05-29T11:17:32.974 INFO (pid:166672) [language-client-index] - Language server "rust-analyzer" started with 166683
2021-05-29T11:17:32.980 ERROR (pid:166672) [language-client-client] - connection error: Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:769:11)
    at Socket._write (node:net:781:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at BM.write (/home/peterlits/.config/nvim/plugged/coc.nvim/build/index.js:26:1009)
    at /home/peterlits/.config/nvim/plugged/coc.nvim/build/index.js:52:2138
    at new Promise (<anonymous>) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
} undefined
2021-05-29T11:17:32.996 INFO (pid:166672) [services] - Rust Analyzer Language Server state change: starting => stopped
2021-05-29T11:17:33.939 INFO (pid:166672) [plugin] - coc.nvim 0.0.80-998c7d8034 initialized with node: v16.2.0 after 1067ms
2021-05-29T11:17:51.627 INFO (pid:166672) [attach] - receive notification: openLog []
```

It looks that It cannot access it by `PIPE`...

This is message that maybe is helpful:
```
peterlits@peterlits-mi-ubuntu:~/.local/bin
 $ ls -l ~/.local/bin/rust-analyzer
-rwxrwxr-x 1 peterlits peterlits 9 May 25 13:08 /home/peterlits/.local/bin/rust-analyzer
```

**Comment by fannheyward** [comment]
What's the output of `~/.local/bin/rust-analyzer --version`?

**Comment by PeterlitsZo** [comment]
> What's the output of `~/.local/bin/rust-analyzer --version`?

:rofl: This is a stupid bug for me:
```
$ ~/.local/bin/rust-analyzer
/home/peterlits/.local/bin/rust-analyzer: 1: Not: not found
$ cat ~/.local/bin/rust-analyzer
Not found
```

Thanks for your kindly help. I think I get it and then I am going to download a analyzer but not a plain `Not found` :rofl:

**Comment by richardtsai** [comment]
Just hit the same `ERR_INVALID_PROTOCOL` issue and I found these: https://github.com/TooTallNate/node-https-proxy-agent/issues/115 and https://github.com/TooTallNate/node-agent-base/pull/47
It seems `agent-base` needs to be upgraded.

**Comment by fannheyward** [comment]
> agent-base needs to be upgraded.

Fixed.

**Comment by PeterlitsZo** [comment]
> Just hit the same `ERR_INVALID_PROTOCOL` issue and I found these: [TooTallNate/node-https-proxy-agent#115](https://github.com/TooTallNate/node-https-proxy-agent/issues/115) and [TooTallNate/node-agent-base#47](https://github.com/TooTallNate/node-agent-base/pull/47)
> It seems `agent-base` needs to be upgraded.

Thanks because it is really useful! I do not install rust-analyzer because I am lazy... But after the owner fix it, I remove the mutual part in `:CocConfig`, run `:CocUpdate`, ans reopen `/tmp/tmp.rs`. It finally works well!
