### ISSUE TITLE
No autoimport suggestions

### ISSUE THREAD

**Issue by Daniikk1012** [fannheyward/coc-rust-analyzer#899]
I use `rustup` + `vim` from official Archlinux repos + `vim-coc` from AUR. Everything works fine, but there are no autoimport suggestions, completions do not list anything that is not already imported. `rust-analyzer.completion.autoimport.enable` is set to `true`. It worked previously and suddenly just stopped and I have no idea why. Switching from `rust` package to `rustup`might be the problem, but I tried to install `rust` package and it still didn't work.

**Comment by fannheyward** [comment]
What's your `:CocCommand rust-analyzer.serverVersion`? Can you reproduce this with VSCode + rust-analyzer? Looks like it's rust-analyzer's issue, the client side can do nothing about this.

**Comment by Daniikk1012** [comment]
It outputs `[coc.nvim] rust-analyzer 2c0f433fd 2021-11-08 stable`. I do not know whether I can reproduce it with VSCode, but probably I will give it a try later. The client side, btw, can do something about this, since rust-analyzer ignores `rust-analyzer.completion.autoimport.enable` being `true` and disables the feature if the client does not send `additionalTextEdits`, if I understand it correctly.

**Comment by fannheyward** [comment]
The client did sending `additionalTextEdits`.

I've tested this, can't reproduce.

1. `cargo new a1 && cd a1`
2. `vim src/main.rs`, input `File` in `main` function, choose and enter to apply:

<img width="426" alt="截屏2021-11-16 下午6 34 01" src="https://user-images.githubusercontent.com/345274/141969534-c97c311a-9bb5-471f-b9d8-db45f4ec0ee7.png">
<img width="380" alt="截屏2021-11-16 下午6 35 23" src="https://user-images.githubusercontent.com/345274/141969736-7e658ed7-5b71-4637-8546-3bc8cb853126.png">

**Comment by Daniikk1012** [comment]
I have just reproduced it in a clean installation. Here are the steps I followed:
1. Install clean Archlinux with `base`, `vim`, `rustup`
2. Install `vim-coc` from AUR
3. `vim` and `:CocInstall coc-rust-analyzer`
3. `rustup default stable`
4. `cargo new al`
5. `cd al`
6. `vim src/main.rs`, input `File`, no import suggestions, only `FromIterator` suggestion when `Fi` is typed

There is also an error every time I launch `vim`, in case it is somehow related:
```
Error detected while processing /usr/share/vim/vimfiles/pack/coc/start/coc.nvim/plugin/coc.vim:
line  438: E1208: -complete used without allowing argumentsPress ENTER or type command to continue
```

**Comment by Daniikk1012** [comment]
Oh it works with the `vim-coc-git`, so I guess it was an issue with `coc.nvim` itself.

**Comment by fannheyward** [comment]
What's the `:CocInfo`?

**Comment by Daniikk1012** [comment]
Here (This is with `vim-coc`, which is made from the latest release of `coc.nvim`. `vim-coc-git` clones the GitHub repository from the latest commit, where the issue seems to be fixed):

```
undefined## versions

vim version: VIM - Vi IMproved 8.2 8023582
node version: v16.11.1
coc.nvim version: 0.0.80-c90a07eec8
coc.nvim directory: /usr/share/vim/vimfiles/pack/coc/start/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2021-11-16T15:04:05.514 INFO (pid:2639) [plugin] - coc.nvim 0.0.80-c90a07eec8 initialized with node: v16.11.1 after 66ms
2021-11-16T15:04:13.945 INFO (pid:2639) [attach] - receive notification: openList [ 'extensions' ]
2021-11-16T15:04:20.561 INFO (pid:2639) [attach] - receive notification: installExtensions [ 'rust-analyzer' ]
2021-11-16T15:04:20.577 INFO (pid:2639) [model-installer] - Using npm from: /usr/bin/yarnpkg
2021-11-16T15:04:20.585 INFO (pid:2639) [model-installer] - Get info from https://registry.npmjs.org/
2021-11-16T15:04:21.189 ERROR (pid:2639) [model-fetch] - Fetch error for https://registry.npmjs.org/rust-analyzer: {
  method: 'GET',
  hostname: 'registry.npmjs.org',
  port: 443,
  path: '/rust-analyzer',
  agent: null,
  rejectUnauthorized: true,
  maxRedirects: 3,
  headers: {
    'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64)',
    'Accept-Encoding': 'gzip, deflate',
    'Proxy-Authorization': null
  },
  timeout: 10000
} Error: Bad response from https://registry.npmjs.org/rust-analyzer: 404
    at RedirectableRequest.<anonymous> (/usr/share/vim/vimfiles/pack/coc/start/coc.nvim/build/index.js:75684:24)
    at RedirectableRequest.emit (node:events:402:35)
    at RedirectableRequest._processResponse (/usr/share/vim/vimfiles/pack/coc/start/coc.nvim/build/index.js:51548:10)
    at ClientRequest.RedirectableRequest._onNativeResponse (/usr/share/vim/vimfiles/pack/coc/start/coc.nvim/build/index.js:51224:10)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:390:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:623:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:487:22)
    at TLSSocket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:199:23)
2021-11-16T15:04:21.193 ERROR (pid:2639) [extensions] - Error on install rust-analyzer Error: Bad response from https://registry.npmjs.org/rust-analyzer: 404
    at RedirectableRequest.<anonymous> (/usr/share/vim/vimfiles/pack/coc/start/coc.nvim/build/index.js:75684:24)
    at RedirectableRequest.emit (node:events:402:35)
    at RedirectableRequest._processResponse (/usr/share/vim/vimfiles/pack/coc/start/coc.nvim/build/index.js:51548:10)
    at ClientRequest.RedirectableRequest._onNativeResponse (/usr/share/vim/vimfiles/pack/coc/start/coc.nvim/build/index.js:51224:10)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:390:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:623:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:487:22)
    at TLSSocket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:199:23)
2021-11-16T15:04:32.681 INFO (pid:2639) [attach] - receive notification: installExtensions [ 'coc-rust-analyzer' ]
2021-11-16T15:04:32.694 INFO (pid:2639) [model-installer] - Using npm from: /usr/bin/yarnpkg
2021-11-16T15:04:32.698 INFO (pid:2639) [model-installer] - Get info from https://registry.npmjs.org/
2021-11-16T15:04:34.861 INFO (pid:2639) [model-installer] - Fetched info of coc-rust-analyzer {
  'dist.tarball': 'https://registry.npmjs.org/coc-rust-analyzer/-/coc-rust-analyzer-0.55.0.tgz',
  'engines.coc': '^0.0.80',
  version: '0.55.0',
  name: 'coc-rust-analyzer'
}
2021-11-16T15:04:34.864 INFO (pid:2639) [model-installer] - Downloading from https://registry.npmjs.org/coc-rust-analyzer/-/coc-rust-analyzer-0.55.0.tgz
2021-11-16T15:04:35.220 INFO (pid:2639) [model-installer] - Download progress 1.2%
2021-11-16T15:04:35.237 INFO (pid:2639) [model-installer] - Download progress 3.1%
2021-11-16T15:04:35.268 INFO (pid:2639) [model-installer] - Download progress 5.1%
2021-11-16T15:04:35.278 INFO (pid:2639) [model-installer] - Download progress 7.0%
2021-11-16T15:04:35.281 INFO (pid:2639) [model-installer] - Download progress 9.0%
2021-11-16T15:04:35.291 INFO (pid:2639) [model-installer] - Download progress 11.0%
2021-11-16T15:04:35.306 INFO (pid:2639) [model-installer] - Download progress 12.9%
2021-11-16T15:04:35.307 INFO (pid:2639) [model-installer] - Download progress 14.9%
2021-11-16T15:04:35.311 INFO (pid:2639) [model-installer] - Download progress 16.8%
2021-11-16T15:04:35.312 INFO (pid:2639) [model-installer] - Download progress 18.8%
2021-11-16T15:04:35.313 INFO (pid:2639) [model-installer] - Download progress 20.7%
2021-11-16T15:04:35.314 INFO (pid:2639) [model-installer] - Download progress 22.7%
2021-11-16T15:04:35.316 INFO (pid:2639) [model-installer] - Download progress 24.6%
2021-11-16T15:04:35.317 INFO (pid:2639) [model-installer] - Download progress 26.6%
2021-11-16T15:04:35.319 INFO (pid:2639) [model-installer] - Download progress 28.6%
2021-11-16T15:04:35.319 INFO (pid:2639) [model-installer] - Download progress 30.5%
2021-11-16T15:04:35.322 INFO (pid:2639) [model-installer] - Download progress 32.5%
2021-11-16T15:04:35.322 INFO (pid:2639) [model-installer] - Download progress 34.4%
2021-11-16T15:04:35.324 INFO (pid:2639) [model-installer] - Download progress 36.4%
2021-11-16T15:04:35.324 INFO (pid:2639) [model-installer] - Download progress 38.3%
2021-11-16T15:04:35.326 INFO (pid:2639) [model-installer] - Download progress 40.3%
2021-11-16T15:04:35.326 INFO (pid:2639) [model-installer] - Download progress 42.2%
2021-11-16T15:04:35.328 INFO (pid:2639) [model-installer] - Download progress 44.2%
2021-11-16T15:04:35.329 INFO (pid:2639) [model-installer] - Download progress 45.9%
2021-11-16T15:04:35.330 INFO (pid:2639) [model-installer] - Download progress 47.9%
2021-11-16T15:04:35.330 INFO (pid:2639) [model-installer] - Download progress 49.8%
2021-11-16T15:04:35.331 INFO (pid:2639) [model-installer] - Download progress 51.8%
2021-11-16T15:04:35.332 INFO (pid:2639) [model-installer] - Download progress 53.8%
2021-11-16T15:04:35.333 INFO (pid:2639) [model-installer] - Download progress 55.7%
2021-11-16T15:04:35.333 INFO (pid:2639) [model-installer] - Download progress 57.7%
2021-11-16T15:04:35.334 INFO (pid:2639) [model-installer] - Download progress 59.6%
2021-11-16T15:04:35.334 INFO (pid:2639) [model-installer] - Download progress 61.6%
2021-11-16T15:04:35.335 INFO (pid:2639) [model-installer] - Download progress 63.5%
2021-11-16T15:04:35.335 INFO (pid:2639) [model-installer] - Download progress 65.5%
2021-11-16T15:04:35.336 INFO (pid:2639) [model-installer] - Download progress 67.4%
2021-11-16T15:04:35.336 INFO (pid:2639) [model-installer] - Download progress 69.4%
2021-11-16T15:04:35.337 INFO (pid:2639) [model-installer] - Download progress 71.3%
2021-11-16T15:04:35.337 INFO (pid:2639) [model-installer] - Download progress 73.3%
2021-11-16T15:04:35.337 INFO (pid:2639) [model-installer] - Download progress 75.3%
2021-11-16T15:04:35.338 INFO (pid:2639) [model-installer] - Download progress 77.2%
2021-11-16T15:04:35.338 INFO (pid:2639) [model-installer] - Download progress 79.2%
2021-11-16T15:04:35.338 INFO (pid:2639) [model-installer] - Download progress 85.2%
2021-11-16T15:04:35.347 INFO (pid:2639) [model-installer] - Download progress 91.3%
2021-11-16T15:04:35.348 INFO (pid:2639) [model-installer] - Download progress 92.7%
2021-11-16T15:04:35.373 INFO (pid:2639) [model-installer] - Download progress 98.8%
2021-11-16T15:04:35.375 INFO (pid:2639) [model-installer] - Download progress 100.0%
2021-11-16T15:04:35.375 INFO (pid:2639) [model-download] - Download completed: https://registry.npmjs.org/coc-rust-analyzer/-/coc-rust-analyzer-0.55.0.tgz
2021-11-16T15:04:35.376 INFO (pid:2639) [model-download] - Downloaded https://registry.npmjs.org/coc-rust-analyzer/-/coc-rust-analyzer-0.55.0.tgz => /tmp/v7l6fO0/coc-rust-analyzer-l1LNo0
2021-11-16T15:04:35.476 INFO (pid:2639) [model-installer] - Extension download at /tmp/v7l6fO0/coc-rust-analyzer-l1LNo0
2021-11-16T15:04:35.515 INFO (pid:2639) [model-installer] - Update package.json at /home/daniyar/.config/coc/extensions/package.json
2021-11-16T15:04:35.515 INFO (pid:2639) [model-installer] - Installed extension coc-rust-analyzer@0.55.0 at /home/daniyar/.config/coc/extensions/node_modules/coc-rust-analyzer
2021-11-16T15:04:36.526 WARN (pid:2639) [extensions] - Extension coc-rust-analyzer activate cost more than 1s
2021-11-16T15:04:44.733 INFO (pid:2639) [attach] - receive notification: showInfo []
2021-11-16T15:04:44.753 INFO (pid:2639) [attach] - receive request: CocAutocmd [ 'BufReadCmd', 'output', 'output:///info' ]
2021-11-16T15:04:45.366 INFO (pid:2639) [services] - registered service "rust-analyzer"
2021-11-16T15:04:45.369 INFO (pid:2639) [services] - Rust Analyzer Language Server state change: stopped => starting
2021-11-16T15:04:45.384 INFO (pid:2639) [language-client-index] - Language server "rust-analyzer" started with 2651
2021-11-16T15:04:45.393 INFO (pid:2639) [services] - Rust Analyzer Language Server state change: starting => running
2021-11-16T15:04:45.401 INFO (pid:2639) [services] - service rust-analyzer started
2021-11-16T15:04:59.789 INFO (pid:2639) [completion-complete] - Results from: rust-analyzer-1
2021-11-16T15:05:00.284 INFO (pid:2639) [attach] - receive notification: stopCompletion []
2021-11-16T15:05:01.903 INFO (pid:2639) [completion-complete] - Results from: rust-analyzer-1
2021-11-16T15:05:06.953 INFO (pid:2639) [attach] - receive notification: showInfo []
```
