### ISSUE TITLE
Rename not working

### ISSUE THREAD

**Issue by Morganamilo** [fannheyward/coc-rust-analyzer#911]
**What's the output of `:CocInfo`**

```
undefined## versions

vim version: VIM - Vi IMproved 8.2 8023582
node version: v17.1.0
coc.nvim version: 0.0.80-c90a07eec8
coc.nvim directory: /usr/share/vim/vimfiles/pack/coc/start/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2021-12-03T16:51:47.241 INFO (pid:3972) [services] - registered service "rust-analyzer"
2021-12-03T16:51:47.242 INFO (pid:3972) [services] - Rust Analyzer Language Server state change: stopped => starting
2021-12-03T16:51:47.262 INFO (pid:3972) [language-client-index] - Language server "rust-analyzer" started with 3983
2021-12-03T16:51:47.266 INFO (pid:3972) [services] - Rust Analyzer Language Server state change: starting => running
2021-12-03T16:51:47.271 INFO (pid:3972) [services] - service rust-analyzer started
2021-12-03T16:51:47.414 INFO (pid:3972) [plugin] - coc.nvim 0.0.80-c90a07eec8 initialized with node: v17.1.0 after 248ms
2021-12-03T16:51:48.149 INFO (pid:3972) [attach] - receive request: CocAutocmd [ 'BufWritePre', 1 ]
2021-12-03T16:51:48.820 INFO (pid:3972) [attach] - receive notification: highlight []
2021-12-03T16:51:53.549 INFO (pid:3972) [attach] - receive notification: highlight []
2021-12-03T16:51:54.590 INFO (pid:3972) [attach] - receive notification: highlight []
2021-12-03T16:51:56.122 INFO (pid:3972) [attach] - receive notification: highlight []
2021-12-03T16:51:57.543 INFO (pid:3972) [attach] - receive notification: rename []
2021-12-03T16:51:58.143 INFO (pid:3972) [attach] - receive notification: highlight []
2021-12-03T16:52:00.492 INFO (pid:3972) [attach] - receive notification: showInfo []
2021-12-03T16:52:00.498 INFO (pid:3972) [attach] - receive request: CocAutocmd [ 'BufReadCmd', 'output', 'output:///info' ]
2021-12-03T16:52:01.107 INFO (pid:3972) [attach] - receive notification: highlight []
2021-12-03T16:52:03.307 INFO (pid:3972) [attach] - receive notification: highlight []
2021-12-03T16:52:04.406 INFO (pid:3972) [attach] - receive notification: highlight []
2021-12-03T16:52:06.341 INFO (pid:3972) [attach] - receive notification: highlight []
2021-12-03T16:52:07.680 INFO (pid:3972) [attach] - receive notification: highlight []
2021-12-03T16:52:09.355 INFO (pid:3972) [attach] - receive request: rename []
2021-12-03T16:52:12.354 ERROR (pid:3972) [attach] - Request cost more than 3s rename []
2021-12-03T16:52:14.093 ERROR (pid:3972) [node-client] - request error on "nvim_call_function" [ 'coc#float#create_prompt_win', [ 'New name', 'a', {} ] ] Vim(call):E21: Cannot make changes, 'modifiable' is off Error
    at NeovimClient.request (/usr/share/vim/vimfiles/pack/coc/start/coc.nvim/build/index.js:15401:21)
    at NeovimClient.call (/usr/share/vim/vimfiles/pack/coc/start/coc.nvim/build/index.js:16294:21)
    at Window.requestInput (/usr/share/vim/vimfiles/pack/coc/start/coc.nvim/build/index.js:44727:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Handler.rename (/usr/share/vim/vimfiles/pack/coc/start/coc.nvim/build/index.js:94845:27)
    at async Plugin.cocAction (/usr/share/vim/vimfiles/pack/coc/start/coc.nvim/build/index.js:23984:16)
    at async NeovimClient.<anonymous> (/usr/share/vim/vimfiles/pack/coc/start/coc.nvim/build/index.js:11532:21)
2021-12-03T16:52:14.094 ERROR (pid:3972) [window] - Error on requestInput: Error
    at NeovimClient.request (/usr/share/vim/vimfiles/pack/coc/start/coc.nvim/build/index.js:15401:21)
    at NeovimClient.call (/usr/share/vim/vimfiles/pack/coc/start/coc.nvim/build/index.js:16294:21)
    at Window.requestInput (/usr/share/vim/vimfiles/pack/coc/start/coc.nvim/build/index.js:44727:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Handler.rename (/usr/share/vim/vimfiles/pack/coc/start/coc.nvim/build/index.js:94845:27)
    at async Plugin.cocAction (/usr/share/vim/vimfiles/pack/coc/start/coc.nvim/build/index.js:23984:16)
    at async NeovimClient.<anonymous> (/usr/share/vim/vimfiles/pack/coc/start/coc.nvim/build/index.js:11532:21)
2021-12-03T16:52:14.097 ERROR (pid:3972) [node-client] - request error on "nvim_call_function" [ 'coc#float#create_prompt_win', [ 'New name', 'a', {} ] ] Vim(call):E21: Cannot make changes, 'modifiable' is off Error
    at NeovimClient.request (/usr/share/vim/vimfiles/pack/coc/start/coc.nvim/build/index.js:15401:21)
    at NeovimClient.call (/usr/share/vim/vimfiles/pack/coc/start/coc.nvim/build/index.js:16294:21)
    at Window.requestInput (/usr/share/vim/vimfiles/pack/coc/start/coc.nvim/build/index.js:44727:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Handler.rename (/usr/share/vim/vimfiles/pack/coc/start/coc.nvim/build/index.js:94845:27)
    at async Plugin.cocAction (/usr/share/vim/vimfiles/pack/coc/start/coc.nvim/build/index.js:23984:16)
    at async NeovimClient.<anonymous> (/usr/share/vim/vimfiles/pack/coc/start/coc.nvim/build/index.js:11557:27)
2021-12-03T16:52:14.098 ERROR (pid:3972) [window] - Error on requestInput: Error
    at NeovimClient.request (/usr/share/vim/vimfiles/pack/coc/start/coc.nvim/build/index.js:15401:21)
    at NeovimClient.call (/usr/share/vim/vimfiles/pack/coc/start/coc.nvim/build/index.js:16294:21)
    at Window.requestInput (/usr/share/vim/vimfiles/pack/coc/start/coc.nvim/build/index.js:44727:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Handler.rename (/usr/share/vim/vimfiles/pack/coc/start/coc.nvim/build/index.js:94845:27)
    at async Plugin.cocAction (/usr/share/vim/vimfiles/pack/coc/start/coc.nvim/build/index.js:23984:16)
    at async NeovimClient.<anonymous> (/usr/share/vim/vimfiles/pack/coc/start/coc.nvim/build/index.js:11557:27)
2021-12-03T16:52:14.734 INFO (pid:3972) [attach] - receive notification: highlight []
2021-12-03T16:52:17.112 INFO (pid:3972) [attach] - receive notification: highlight []
2021-12-03T16:52:18.117 INFO (pid:3972) [attach] - receive notification: highlight []
2021-12-03T16:52:20.298 INFO (pid:3972) [attach] - receive notification: showInfo []
```

**What's the output of `:CocCommand rust-analyzer.serverVersion`**
[coc.nvim] rust-analyzer d9b2291f5 2021-11-29 stable

Renaming doesn't work. It used to work at *some* point but doesn't any more.

I've also noticed `coc-codeaction-cursor` doesn't work and I'm not sure if there's any relation. `coc-codeaction-selection` does work however.

**Comment by fannheyward** [comment]
> 'modifiable' is off

Did you do renaming on a read-only file?

**Comment by Morganamilo** [comment]
Nope file is writable. Also still happens after updating, though now the box pops up for a milisecond before going away

![image](https://user-images.githubusercontent.com/16593899/144814366-6a410546-c8a1-4416-a781-539ba7a99352.png)

**Comment by Morganamilo** [comment]
Also no error in the log this time, though i am using a differrent pc:

```
## versions

vim version: VIM - Vi IMproved 8.2 8023582
node version: v17.1.0
coc.nvim version: 0.0.80-0219acc58d
coc.nvim directory: /usr/share/vim/vimfiles/pack/coc/start/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2021-12-06T08:41:41.529 INFO (pid:120786) [services] - registered service "highlight"
2021-12-06T08:41:41.549 INFO (pid:120786) [services] - registered service "rust-analyzer"
2021-12-06T08:41:41.550 INFO (pid:120786) [services] - Rust Analyzer Language Server state change: stopped => starting
2021-12-06T08:41:41.551 INFO (pid:120786) [plugin] - coc.nvim 0.0.80-0219acc58d initialized with node: v17.1.0 after 64ms
2021-12-06T08:41:41.561 INFO (pid:120786) [language-client-index] - Language server "rust-analyzer" started with 120805
2021-12-06T08:41:41.565 INFO (pid:120786) [services] - Rust Analyzer Language Server state change: starting => running
2021-12-06T08:41:41.570 INFO (pid:120786) [services] - service rust-analyzer started
2021-12-06T08:41:46.418 INFO (pid:120786) [completion-complete] - Results from: rust-analyzer
2021-12-06T08:41:50.058 INFO (pid:120786) [completion-complete] - Results from: rust-analyzer
2021-12-06T08:41:52.763 INFO (pid:120786) [attach] - receive notification: highlight []
2021-12-06T08:41:55.753 INFO (pid:120786) [attach] - receive notification: highlight []
2021-12-06T08:41:57.011 INFO (pid:120786) [attach] - receive notification: highlight []
2021-12-06T08:41:57.520 INFO (pid:120786) [attach] - receive notification: rename []
2021-12-06T08:41:58.226 INFO (pid:120786) [attach] - receive notification: highlight []
2021-12-06T08:41:58.526 INFO (pid:120786) [attach] - receive notification: rename []
2021-12-06T08:41:59.236 INFO (pid:120786) [attach] - receive notification: highlight []
2021-12-06T08:42:01.491 INFO (pid:120786) [attach] - receive notification: showInfo []
```

**Comment by fannheyward** [comment]
> 0.0.80-c90a07eec8

Upgrade your coc.nvim please, you're using an old release.

> 0.0.80-0219acc58d

This is a new release.

**Comment by Morganamilo** [comment]
Same on that version. Though the latest release is still 0.0.80-c90a07eec8 https://github.com/neoclide/coc.nvim/releases/tag/v0.0.80

**Comment by fannheyward** [comment]
You should use the release branch https://github.com/neoclide/coc.nvim/tree/release

**Comment by Morganamilo** [comment]
Same thing with release branch. Why did you close this?

**Comment by fannheyward** [comment]
> Same thing with release branch

When you use the release branch, what's your `CocInfo` now?

**Comment by Morganamilo** [comment]
```
## versions

vim version: VIM - Vi IMproved 8.2 8023582
node version: v17.1.0
coc.nvim version: 0.0.80-03c9add7cd
coc.nvim directory: /usr/share/vim/vimfiles/pack/coc/start/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2021-12-06T11:32:39.133 INFO (pid:4615) [services] - registered service "rust-analyzer"
2021-12-06T11:32:39.137 INFO (pid:4615) [services] - Rust Analyzer Language Server state change: stopped => starting
2021-12-06T11:32:39.162 INFO (pid:4615) [plugin] - coc.nvim 0.0.80-03c9add7cd initialized with node: v17.1.0 after 276ms
2021-12-06T11:32:39.185 INFO (pid:4615) [language-client-index] - Language server "rust-analyzer" started with 4626
2021-12-06T11:32:39.215 INFO (pid:4615) [services] - Rust Analyzer Language Server state change: starting => running
2021-12-06T11:32:39.235 INFO (pid:4615) [services] - service rust-analyzer started
2021-12-06T11:32:41.831 INFO (pid:4615) [attach] - receive notification: highlight []
2021-12-06T11:32:43.259 WARN (pid:4615) [plugin] - Slow action "highlight" cost 1427ms
2021-12-06T11:32:43.937 INFO (pid:4615) [attach] - receive notification: highlight []
2021-12-06T11:32:44.896 WARN (pid:4615) [plugin] - Slow action "highlight" cost 958ms
2021-12-06T11:32:45.494 INFO (pid:4615) [attach] - receive notification: highlight []
2021-12-06T11:33:26.951 INFO (pid:4615) [attach] - receive notification: highlight []
2021-12-06T11:33:32.412 INFO (pid:4615) [attach] - receive notification: rename []
2021-12-06T11:33:33.014 INFO (pid:4615) [attach] - receive notification: highlight []
2021-12-06T11:33:33.015 WARN (pid:4615) [plugin] - Slow action "highlight" cost 6063ms
2021-12-06T11:33:33.810 WARN (pid:4615) [plugin] - Slow action "highlight" cost 796ms
2021-12-06T11:33:33.922 WARN (pid:4615) [plugin] - Slow action "rename" cost 1509ms
2021-12-06T11:33:35.455 INFO (pid:4615) [attach] - receive notification: rename []
2021-12-06T11:33:36.145 INFO (pid:4615) [attach] - receive notification: highlight []
2021-12-06T11:33:36.820 INFO (pid:4615) [attach] - receive notification: rename []
2021-12-06T11:33:37.382 INFO (pid:4615) [attach] - receive notification: rename []
2021-12-06T11:33:37.770 INFO (pid:4615) [attach] - receive notification: rename []
2021-12-06T11:33:38.093 INFO (pid:4615) [attach] - receive notification: rename []
2021-12-06T11:33:38.288 INFO (pid:4615) [attach] - receive notification: rename []
2021-12-06T11:33:38.449 INFO (pid:4615) [attach] - receive notification: rename []
2021-12-06T11:33:38.597 INFO (pid:4615) [attach] - receive notification: rename []
2021-12-06T11:33:39.262 INFO (pid:4615) [attach] - receive notification: highlight []
2021-12-06T11:33:41.255 INFO (pid:4615) [attach] - receive notification: showInfo []
```

**Comment by fannheyward** [comment]
1. set `rust-analyzer.trace.server` to `verbose` in your coc-settings.json
2. do renaming work
3. open `:CocCommand workspace.showOutput`
4. search `textDocument/prepareRename` and `textDocument/rename` in the logs, you should got pairs request and response

I still can't reproduce the issue.

**Comment by Morganamilo** [comment]
I see nothing really interesting:

```
[Trace - 11:54:08 AM] Sending request 'textDocument/prepareRename - (13)'.                          
Params: {                                                                                           
    "textDocument": {                                                                               
        "uri": "file:///mnt/c/Users/GRD-User/git/stream-processor/stream-processor/src/moment.rs"   
    },                                                                                              
    "position": {                                                                                   
        "line": 65,                                                                                 
        "character": 12                                                                             
    }                                                                                               
}                                                                                                   
                                                                                                    
                                                                                                    
[Trace - 11:54:08 AM] Received response 'textDocument/prepareRename - (13)' in 3ms.                 
Result: {                                                                                           
    "start": {                                                                                      
        "line": 65,                                                                                 
        "character": 10                                                                             
    },                                                                                              
    "end": {                                                                                        
        "line": 65,                                                                                 
        "character": 16                                                                             
    }                                                                                               
}                                                                                                   
```

The issue is that the rename pops up for split second and disappears. So I think the issue may not be with the server but the box being closed instantly for some reason.

This always pops up at the bottom after `"file.rs" 107 lines --46%--` which could be releated.

**Comment by fannheyward** [comment]
The logs show that it's not a server issue.

Try minimal vimrc, keep coc.nvim and coc-rust-analzyer only, to reproduce this.

**Comment by Morganamilo** [comment]
For the record, I tested it in neo vim and it works there.

**Comment by fannheyward** [comment]
Tested with `VIM - Vi IMproved 8.2 8023750`, still can't reproduce this, the renaming works as expected, the pops will show and not disappear.
