### ISSUE TITLE
[coc.nvim]: UnhandledRejection: write EPIPE

### ISSUE THREAD

**Issue by igorsol** [fannheyward/coc-rust-analyzer#962]
When I open a "main.rs" of a simple rust project in neovim I have following output at the bottom of the terminal:
```
[coc.nvim]: UnhandledRejection: write EPIPE                                                                                                                                                               
Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:795:11)
    at Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at /home/igor/.local/share/nvim/plugged/coc.nvim/build/index.js:36:3107
    at new Promise (<anonymous>)
    at K1.write (/home/igor/.local/share/nvim/plugged/coc.nvim/build/index.js:36:3028)
Press ENTER or type command to continue
```
I tried to reinstall coc-rust-analyzer but without result. Can you please help to debug this.

**What's the output of `:CocInfo`**
```
## versions

vim version: NVIM v0.6.0-dev
node version: v16.14.2
coc.nvim version: 0.0.80-12d84da5 2022-03-21 18:11:22 +0800
coc.nvim directory: /home/igor/.local/share/nvim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2022-03-21T18:56:41.124 ERROR (pid:6925) [configurations] - Ignoring rust-analyzer.inlayHints.lifetimeElisionHints.useParameterNames as rust-analyzer.inlayHints.lifetimeElisionHints is "never"
2022-03-21T18:56:41.169 INFO (pid:6925) [plugin] - coc.nvim initialized with node: v16.14.2 after 70ms
2022-03-21T18:56:46.774 INFO (pid:6925) [services] - registered service "rust-analyzer"
2022-03-21T18:56:46.775 INFO (pid:6925) [services] - Rust Analyzer Language Server state change: stopped => starting
2022-03-21T18:56:46.785 INFO (pid:6925) [language-client-index] - Language server "rust-analyzer" started with 6957
2022-03-21T18:56:46.794 ERROR (pid:6925) [language-client-client] - connection error: Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:795:11)
    at Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at /home/igor/.local/share/nvim/plugged/coc.nvim/build/index.js:36:3107
    at new Promise (<anonymous>)
    at K1.write (/home/igor/.local/share/nvim/plugged/coc.nvim/build/index.js:36:3028) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
} undefined
2022-03-21T18:56:46.806 INFO (pid:6925) [services] - Rust Analyzer Language Server state change: starting => stopped
2022-03-21T18:56:46.807 ERROR (pid:6925) [language-client-client] - connection error: Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:795:11)
    at Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at /home/igor/.local/share/nvim/plugged/coc.nvim/build/index.js:36:3107
    at new Promise (<anonymous>)
    at K1.write (/home/igor/.local/share/nvim/plugged/coc.nvim/build/index.js:36:3028) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
} {
  jsonrpc: '2.0',
  id: 0,
  method: 'initialize',
  params: {
    processId: 6925,
    rootPath: '/home/igor/repo/test802',
    rootUri: 'file:///home/igor/repo/test802',
    capabilities: {
      workspace: [Object],
      textDocument: [Object],
      window: [Object],
      general: [Object],
      experimental: [Object]
    },
    initializationOptions: {
      enable: true,
      terminal: [Object],
      debug: [Object],
      inlayHints: [Object],
      trace: [Object],
      updates: [Object],
      assist: [Object],
      cache: [Object],
      callInfo: [Object],
      cargo: [Object],
      checkOnSave: [Object],
      completion: [Object],
      diagnostics: [Object],
      experimental: [Object],
      files: [Object],
      highlightRelated: [Object],
      highlighting: [Object],
      hover: [Object],
      hoverActions: [Object],
      joinLines: [Object],
      lens: [Object],
      linkedProjects: [],
      notifications: [Object],
      primeCaches: [Object],
      procMacro: [Object],
      runnables: [Object],
      rustfmt: [Object],
      workspace: [Object]
    },
    trace: 'off',
    workspaceFolders: [ [Object] ],
    locale: 'en_US',
    clientInfo: { name: 'coc.nvim', version: '0.0.80' }
  }
}
2022-03-21T18:56:46.808 ERROR (pid:6925) [server] - unhandledRejection  Promise {
  <rejected> Error: write EPIPE
      at afterWriteDispatched (node:internal/stream_base_commons:160:15)
      at writeGeneric (node:internal/stream_base_commons:151:3)
      at Socket._writeGeneric (node:net:795:11)
      at Socket._write (node:net:807:8)
      at writeOrBuffer (node:internal/streams/writable:389:12)
      at _write (node:internal/streams/writable:330:10)
      at Socket.Writable.write (node:internal/streams/writable:334:10)
      at /home/igor/.local/share/nvim/plugged/coc.nvim/build/index.js:36:3107
      at new Promise (<anonymous>)
      at K1.write (/home/igor/.local/share/nvim/plugged/coc.nvim/build/index.js:36:3028) {
    errno: -32,
    code: 'EPIPE',
    syscall: 'write'
  }
} Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:795:11)
    at Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at /home/igor/.local/share/nvim/plugged/coc.nvim/build/index.js:36:3107
    at new Promise (<anonymous>)
    at K1.write (/home/igor/.local/share/nvim/plugged/coc.nvim/build/index.js:36:3028) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
2022-03-21T18:56:46.811 ERROR (pid:6925) [language-client-client] - connection error: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at new NodeError (node:internal/errors:371:5)
    at _write (node:internal/streams/writable:321:11)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at /home/igor/.local/share/nvim/plugged/coc.nvim/build/index.js:36:3107
    at new Promise (<anonymous>)
    at K1.write (/home/igor/.local/share/nvim/plugged/coc.nvim/build/index.js:36:3028)
    at VS.doWrite (/home/igor/.local/share/nvim/plugged/coc.nvim/build/index.js:37:1698)
    at /home/igor/.local/share/nvim/plugged/coc.nvim/build/index.js:37:1597 {
  code: 'ERR_STREAM_DESTROYED'
} { jsonrpc: '2.0', id: 1, method: 'shutdown', params: undefined }
2022-03-21T18:56:46.811 ERROR (pid:6925) [server] - unhandledRejection  Promise {
  <rejected> Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
      at new NodeError (node:internal/errors:371:5)
      at _write (node:internal/streams/writable:321:11)
      at Socket.Writable.write (node:internal/streams/writable:334:10)
      at /home/igor/.local/share/nvim/plugged/coc.nvim/build/index.js:36:3107
      at new Promise (<anonymous>)
      at K1.write (/home/igor/.local/share/nvim/plugged/coc.nvim/build/index.js:36:3028)
      at VS.doWrite (/home/igor/.local/share/nvim/plugged/coc.nvim/build/index.js:37:1698)
      at /home/igor/.local/share/nvim/plugged/coc.nvim/build/index.js:37:1597 {
    code: 'ERR_STREAM_DESTROYED'
  }
} Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at new NodeError (node:internal/errors:371:5)
    at _write (node:internal/streams/writable:321:11)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at /home/igor/.local/share/nvim/plugged/coc.nvim/build/index.js:36:3107
    at new Promise (<anonymous>)
    at K1.write (/home/igor/.local/share/nvim/plugged/coc.nvim/build/index.js:36:3028)
    at VS.doWrite (/home/igor/.local/share/nvim/plugged/coc.nvim/build/index.js:37:1698)
    at /home/igor/.local/share/nvim/plugged/coc.nvim/build/index.js:37:1597 {
  code: 'ERR_STREAM_DESTROYED'
}
2022-03-21T18:56:48.814 ERROR (pid:6925) [services] - Server rust-analyzer failed to start: Error: Connection got disposed.
    at Object.dispose (/home/igor/.local/share/nvim/plugged/coc.nvim/build/index.js:63:4169)
    at Object.dispose (/home/igor/.local/share/nvim/plugged/coc.nvim/build/index.js:212:6601)
    at Timeout._onTimeout (/home/igor/.local/share/nvim/plugged/coc.nvim/build/index.js:217:6522)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
2022-03-21T18:56:48.815 ERROR (pid:6925) [extensions] - Error on active extension coc-rust-analyzer: Connection got disposed. Error: Connection got disposed.
    at Object.dispose (/home/igor/.local/share/nvim/plugged/coc.nvim/build/index.js:63:4169)
    at Object.dispose (/home/igor/.local/share/nvim/plugged/coc.nvim/build/index.js:212:6601)
    at Timeout._onTimeout (/home/igor/.local/share/nvim/plugged/coc.nvim/build/index.js:217:6522)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
2022-03-21T18:58:33.093 INFO (pid:6925) [attach] - receive notification: showInfo []
```
**What's the output of `:CocCommand rust-analyzer.serverVersion`**
This command does not produce any output

**Comment by PPakalns** [comment]
In my case this error was caused because rust-analyzer that was downloaded by coc-rust-analyzer plugin was compiled in different environment (with never symbol versions).

This can be fixed by compiling and installing rust-analyzer locally and setting rust-analyzer.server.path to "rust-analyzer" in :CocConfig configuration.

**Comment by fannheyward** [comment]
> write EPIPE

Looks like your `rust-analyzer` couldn't work. coc-rust-analyzer will download RA from GitHub and save to `~/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer`, check it, what's the output of

`~/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer --version`?

**Comment by fannheyward** [comment]
>  because rust-analyzer that was downloaded by coc-rust-analyzer plugin was compiled in different environment

coc-rust-analyzer will download RA from https://github.com/rust-analyzer/rust-analyzer/releases

**Comment by igorsol** [comment]
```
$ ~/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer --version
/home/igor/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /home/igor/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer)
```
It looks like I should follow @PPakalns suggestion and try to build rust analyzer locally.

**Comment by igorsol** [comment]
Ok, I resolved this issue using local build of rust analyzer.
It looks like the source of an issue is the version of my OS: I still run this neovim instance on Ubuntu 16.04 but rust-analyzer builds were moved to Ubuntu 18.04 recently.
Yes, I know Ununtu 16.04 has reached its EOL.
