### ISSUE TITLE
Autoimport imports local modules twice

### ISSUE THREAD

**Issue by uwumouse** [fannheyward/coc-rust-analyzer#976]
When I try to import local module, it imports it twice for some reason (some other libs that not belong to my project is auto-imported normally):
![image](https://user-images.githubusercontent.com/61386270/165622769-900aadce-4c08-48ed-88d4-33ee1e5a4874.png)
Then I hit `Enter`:
![image](https://user-images.githubusercontent.com/61386270/165622819-9082688e-1c04-4244-8e5c-4cc95e7365e2.png)

**What's the output of `:CocInfo`**
```
## versions

vim version: NVIM v0.7.0
node version: v16.14.2
coc.nvim version: 0.0.80-3dc25e03 2022-03-29 23:12:08 +0800
coc.nvim directory: /home/mouse/.vim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2022-04-27T23:01:43.134 INFO (pid:176068) [plugin] - coc.nvim initialized with node: v16.14.2 after 414ms
2022-04-27T23:01:43.892 INFO (pid:176068) [attach] - receive notification: highlight []
2022-04-27T23:01:44.254 INFO (pid:176068) [attach] - receive notification: highlight []
2022-04-27T23:01:45.883 INFO (pid:176068) [attach] - receive notification: highlight []
2022-04-27T23:01:48.380 WARN (pid:176068) [workspace] - workspace.createStatusBarItem is deprecated, please use window.createStatusBarItem instead. 
    at Object.<anonymous> (/home/mouse/.config/coc/extensions/node_modules/coc-rls/lib/index.js:5711:39)
    at __webpack_require__ (/home/mouse/.config/coc/extensions/node_modules/coc-rls/lib/index.js:20:30)
2022-04-27T23:01:48.382 WARN (pid:176068) [workspace] - workspace.createOutputChannel is deprecated, please use window.createOutputChannel instead. 
    at Object.<anonymous> (/home/mouse/.config/coc/extensions/node_modules/coc-rls/lib/index.js:131:44)
    at Generator.next (<anonymous>)
2022-04-27T23:01:48.395 INFO (pid:176068) [services] - registered service "rust-client"
2022-04-27T23:01:48.472 INFO (pid:176068) [services] - registered service "rust-analyzer"
2022-04-27T23:01:48.472 INFO (pid:176068) [services] - Rust Analyzer Language Server state change: stopped => starting
2022-04-27T23:01:48.606 INFO (pid:176068) [extension:coc-rls] - Detected active channel: stable-x86_64-unknown-linux-gnu (since 'rust-client.channel' is unspecified)
2022-04-27T23:01:48.645 INFO (pid:176068) [language-client-index] - Language server "rust-analyzer" started with 176099
2022-04-27T23:01:48.671 INFO (pid:176068) [services] - Rust Analyzer Language Server state change: starting => running
2022-04-27T23:01:48.684 INFO (pid:176068) [services] - service rust-analyzer started
2022-04-27T23:01:48.878 INFO (pid:176068) [extension:coc-rls] - Detected active channel: stable-x86_64-unknown-linux-gnu (since 'rust-client.channel' is unspecified)
2022-04-27T23:01:49.404 INFO (pid:176068) [attach] - Request action: diagnosticList []
2022-04-27T23:01:53.188 INFO (pid:176068) [attach] - Request action: diagnosticList []
2022-04-27T23:02:00.586 INFO (pid:176068) [attach] - receive notification: highlight []
2022-04-27T23:02:02.713 INFO (pid:176068) [completion-complete] - 0 results from: 
2022-04-27T23:02:02.714 INFO (pid:176068) [attach] - Request action: doKeymap [ 'iPGJzPg==0' ]
2022-04-27T23:02:02.856 INFO (pid:176068) [attach] - Request action: doKeymap [ 'iPGJzPg==0' ]
2022-04-27T23:02:03.886 INFO (pid:176068) [completion-complete] - 3 results from: snippets,rust-client,rust-analyzer
2022-04-27T23:02:04.115 INFO (pid:176068) [completion-complete] - 3 results from: snippets,rust-client,rust-analyzer
2022-04-27T23:02:04.381 INFO (pid:176068) [completion-complete] - 3 results from: snippets,rust-client,rust-analyzer
2022-04-27T23:02:39.865 INFO (pid:176068) [completion-complete] - 0 results from: 
2022-04-27T23:02:41.341 INFO (pid:176068) [attach] - Request action: diagnosticList []
2022-04-27T23:02:41.650 INFO (pid:176068) [attach] - receive notification: highlight []
2022-04-27T23:02:43.040 INFO (pid:176068) [attach] - Request action: diagnosticList []
2022-04-27T23:02:44.500 INFO (pid:176068) [attach] - receive notification: showInfo []
```

**What's the output of `:CocCommand rust-analyzer.serverVersion`**
![image](https://user-images.githubusercontent.com/61386270/165622605-e360f57d-711d-467f-bce6-513691e32c28.png)

[My nvim config](https://github.com/uwumouse/dotfiles/blob/4bc2ff61bef0b2828556decf9c1db37d864c2d61/.config/nvim/init.vim#L184)

**Comment by fannheyward** [comment]
You're using `coc-rls` and `coc-rust-analyzer`, you shouldn't use them at same time, disable one and try again.

**Comment by uwumouse** [comment]
I've done `:CocUninstall coc-rls` and the problem is still present. Now in `:CocInfo` it says this:
```
2022-04-28T15:03:55.667 INFO (pid:180079) [completion-complete] - 1 results from: rust-analyzer
```
So  as I understood, `rust-analyzer` is the only extension that will do completion. But "double import" still happens.

**Comment by fannheyward** [comment]
Can you reproduce this with VS Code + rust-analyzer? If so, it's an issue of rust-analyzer.

Set `"rust-analyzer.trace.server": "verbose"` in your coc-settings.json, and when reproduce this issue, checkout `:CocCommand workspace.showOutput rust-analyzer`.

**Comment by fannheyward** [comment]
Reproduced, but looks like it's rust-analyzer's issue:

```
"additionalTextEdits": [
        {
            "range": {
                "start": {
                    "line": 2,
                    "character": 0
                },
                "end": {
                    "line": 2,
                    "character": 0
                }
            },
            "newText": "use commands::Command;"
        },
        {
            "range": {
                "start": {
                    "line": 2,
                    "character": 0
                },
                "end": {
                    "line": 2,
                    "character": 0
                }
            },
            "newText": "\n"
        },
        {
            "range": {
                "start": {
                    "line": 2,
                    "character": 0
                },
                "end": {
                    "line": 2,
                    "character": 0
                }
            },
            "newText": "use commands::Command;"
        },
        {
            "range": {
                "start": {
                    "line": 2,
                    "character": 0
                },
                "end": {
                    "line": 2,
                    "character": 0
                }
            },
            "newText": "\n"
        }
    ]
```

RA returns two `use commands::Command;` textEdits, coc/coc-rust-analyzer applied them.

**Comment by uwumouse** [comment]
Any progress on this?

**Comment by uwumouse** [comment]
Oh, then I should probably go to rust-analyzers repo with  my issue.
Thanks for help!

**Comment by alansartorio** [comment]
I think I found where this problem is coming from, I opened an issue in coc.nvim [here](https://github.com/neoclide/coc.nvim/issues/3917).
